### ISSUE TITLE
FLATDN keyword in level 1 seems incorrect

### ISSUE THREAD

**Issue by detoma** [NCAR/ucomp-pipeline#111]
I cannot convert DN to level1 calibrated data using FLATDN. I checked the intermediate steps and FLATDN seems to change value between step 09-find alignment and step 10-continuum subtraction. There is about a factor of 2 difference.

**Comment by mgalloy** [comment]
When combining extensions in the continuum subtraction, I forgot to divide the `FLATDN` values by 2.
