### ISSUE TITLE
Level 1 centering and alignment not working well

### ISSUE THREAD

**Issue by detoma** [NCAR/ucomp-pipeline#112]
I randomly tested the alignment of 1074 image in the two cameras using the special runs with imtermediate products that MIke did for me, in the step just before the cameras are combined. The images are not well aligned (see example below). It seems the problem is because the routine that fits a circle to the occulter and finds the center often fails to find the correct fit. The gif images that have the circle fit overplotted to the UCOMP image show that the circle is off in many images, in some cases by several pixels (see example below). If I interpret the plots correctly, the centering code is not working.

<img width="1117" alt="misalignment" src="https://github.com/NCAR/ucomp-pipeline/assets/12946149/68a55274-6050-455c-9657-7fca5ab1375f">

![circlefit](https://github.com/NCAR/ucomp-pipeline/assets/12946149/ae56a7c7-7443-4e91-acd0-f7fc48cb16e0)

**Comment by detoma** [comment]
The misalignment of the corona in the two cameras is real but the circle not fitting the occulter was a plotting issue.

We now think the mis-alignment of the corona in the two cameras is largely driven by drift -due to bad pointing, bad seeing or wind- during the time we acquire the level 0 data that are combined to create  a level 1 file.

**Comment by jburkepile** [comment]
I am closing this ticket at Giuliana's suggestion. See her comment above.
