### ISSUE TITLE
Fix display of centering annotations

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#116]
There are a couple of fixes needed for the display on both the intermediate and final GIFs:

- [x] annotations to indicate which color indicates what
- [x] the guesses (center and circle) are not transformed correctly to be shown on the display
- [x] don't display centering annotations on enhanced intensity (it won't match up)
- [x] the occulter center and circle is not transformed correctly in the intermediate images
- [x] don't display guesses on final level 1 GIF

**Comment by mgalloy** [comment]
Maybe the guesses shouldn't be displayed at all?

**Comment by mgalloy** [comment]
The annotations are correct after the apply alignment step. Maybe only display the annotations after this step?

**Comment by mgalloy** [comment]
So now intermediate steps before apply alignment step don't show any centering annotations. That fixes any bad displays, but maybe I should fix the pre-aligned displays?

**Comment by detoma** [comment]
We want to check the centering before the two cameras are combined. It is instructive to show the range that was used to find the inflection points.
