### ISSUE TITLE
num_wave keyword value incorrect

### ISSUE THREAD

**Issue by jburkepile** [NCAR/ucomp-pipeline#132]
The num_wave fits keyword for this image is incorrect:
     
    20220226.ucomp.1074.l2.synoptic.mean.fts

The header has num_wave = 6 but it should be num_wave=3.

I do not know how many other cases exist of this problem. This issue can wait until post-SHINE when we have more time.

There should be checks for the correct wavelengths:

- [x] quality check that rejects science files with wavelengths not in the same wave region
- [x] ~~`UCOMP_AVERAGE_L1_FILES` should reject files that don't all have the same wavelengths~~ (actually it handles it correctly — it takes pains to average like wavelengths and all wavelengths not have the same number of files in their average if files with multiple number of wavelengths are passed in)

**Comment by detoma** [comment]
If there is a synoptic median file num_waves should be 5, but it does not look like we run the synoptic program that day. All 1074 observations had 3 points according to the daily catalog.

**Comment by jburkepile** [comment]
Agreed - Giuliana. I don't know why NUM_WAVE is incorrect.

The size of the level 0 files changes between 20220226.205103.66.ucomp.1074.l0.fts 
and 20220226.210903.81.ucomp.1074.l0.fts.    Images taken at 21:09:03 and later are 4 times larger than 1074 images acquired earlier in day, but they are all 3 points.
I looked at the extension headers to validate they are all 3 point data. Data starting at 21:09:03 simply acquired 4 times as many 'samples' of 3 point data per fits image.

In case it might help Mike to troubleshoot, here are the names of the observing plans:
The OBS_PLAN name in the header for the 20:51:03 image is: 'waves_1074_1hour.cbk'
The OBS_PLAN name in the header for the 21:09:03 image is:  'all_wavelenght_coronal.cbk'

**Comment by mgalloy** [comment]
It is because this "1074" file actually has 1079 nm data, so the code sees 6 unique wavelengths:

    20220227.003322.ucomp.1074.l1.3.fts            3  all_wavelenght_coronal.cbk
      1  1079.69
      2  1079.80
      3  1079.91
      4  1079.69
      5  1079.80
      6  1079.91

**Comment by mgalloy** [comment]
I can mark that file to not be processed. I don't see any others that day.

**Comment by mgalloy** [comment]
a7fc39efb764f2ead729e08b4ebed2dfffc30607 adds a quality check to make sure `WAVELNG` values match `FILTER` value.
