### ISSUE TITLE
Azimuth png files appear to small 320x256

### ISSUE THREAD

**Issue by bberkeyU** [NCAR/ucomp-pipeline#133]
We found that some of the reprocessed standalone azimuth png files have are 320x256 pixels while the other standalone L2 quantities are 1280x1024 pixels.

This issue was found in the following directories:

/hao/dawn/Data/UCoMP/process/20210805
/hao/dawn/Data/UCoMP/process/20210806
/hao/dawn/Data/UCoMP/process/20210807
/hao/dawn/Data/UCoMP/process/20210808
/hao/dawn/Data/UCoMP/process/20210810
/hao/dawn/Data/UCoMP/process/20210812
/hao/dawn/Data/UCoMP/process/20210814
/hao/dawn/Data/UCoMP/process/20210816
/hao/dawn/Data/UCoMP/process/20210817
/hao/dawn/Data/UCoMP/process/20210818
/hao/dawn/Data/UCoMP/process/20210819
/hao/dawn/Data/UCoMP/process/20210820
/hao/dawn/Data/UCoMP/process/20210821
/hao/dawn/Data/UCoMP/process/20210822
/hao/dawn/Data/UCoMP/process/20210904
/hao/dawn/Data/UCoMP/process/20210905
/hao/dawn/Data/UCoMP/process/20210906
/hao/dawn/Data/UCoMP/process/20210907
/hao/dawn/Data/UCoMP/process/20210908
/hao/dawn/Data/UCoMP/process/20210911
/hao/dawn/Data/UCoMP/process/20210912
/hao/dawn/Data/UCoMP/process/20210913
/hao/dawn/Data/UCoMP/process/20210914
/hao/dawn/Data/UCoMP/process/20210915
/hao/dawn/Data/UCoMP/process/20210917
/hao/dawn/Data/UCoMP/process/20210918
/hao/dawn/Data/UCoMP/process/20210921
/hao/dawn/Data/UCoMP/process/20210922
/hao/dawn/Data/UCoMP/process/20211010
/hao/dawn/Data/UCoMP/process/20211011
/hao/dawn/Data/UCoMP/process/20211015
/hao/dawn/Data/UCoMP/process/20211016
/hao/dawn/Data/UCoMP/process/20211018
/hao/dawn/Data/UCoMP/process/20211019
/hao/dawn/Data/UCoMP/process/20211020
/hao/dawn/Data/UCoMP/process/20211022
/hao/dawn/Data/UCoMP/process/20211101
/hao/dawn/Data/UCoMP/process/20211102
/hao/dawn/Data/UCoMP/process/20211103
/hao/dawn/Data/UCoMP/process/20211104
/hao/dawn/Data/UCoMP/process/20211107
/hao/dawn/Data/UCoMP/process/20211108
/hao/dawn/Data/UCoMP/process/20211110
/hao/dawn/Data/UCoMP/process/20211111
/hao/dawn/Data/UCoMP/process/20211119
/hao/dawn/Data/UCoMP/process/20211120
/hao/dawn/Data/UCoMP/process/20211122
/hao/dawn/Data/UCoMP/process/20211123
/hao/dawn/Data/UCoMP/process/20211124
/hao/dawn/Data/UCoMP/process/20211125
/hao/dawn/Data/UCoMP/process/20211127
/hao/dawn/Data/UCoMP/process/20211128
/hao/dawn/Data/UCoMP/process/20211202
/hao/dawn/Data/UCoMP/process/20211211
/hao/dawn/Data/UCoMP/process/20211212
/hao/dawn/Data/UCoMP/process/20211213
/hao/dawn/Data/UCoMP/process/20211214
/hao/dawn/Data/UCoMP/process/20211215
/hao/dawn/Data/UCoMP/process/20211217
/hao/dawn/Data/UCoMP/process/20211218
/hao/dawn/Data/UCoMP/process/20211224
/hao/dawn/Data/UCoMP/process/20211225
/hao/dawn/Data/UCoMP/process/20211226
/hao/dawn/Data/UCoMP/process/20220101
/hao/dawn/Data/UCoMP/process/20220104
/hao/dawn/Data/UCoMP/process/20220105
/hao/dawn/Data/UCoMP/process/20220106
/hao/dawn/Data/UCoMP/process/20220107
/hao/dawn/Data/UCoMP/process/20220108
/hao/dawn/Data/UCoMP/process/20220109
/hao/dawn/Data/UCoMP/process/20220110
/hao/dawn/Data/UCoMP/process/20220111
/hao/dawn/Data/UCoMP/process/20220112
/hao/dawn/Data/UCoMP/process/20220113
/hao/dawn/Data/UCoMP/process/20220115
/hao/dawn/Data/UCoMP/process/20220116
/hao/dawn/Data/UCoMP/process/20220117
/hao/dawn/Data/UCoMP/process/20220118
/hao/dawn/Data/UCoMP/process/20220119
/hao/dawn/Data/UCoMP/process/20220120
/hao/dawn/Data/UCoMP/process/20220121
/hao/dawn/Data/UCoMP/process/20220201
/hao/dawn/Data/UCoMP/process/20220202
/hao/dawn/Data/UCoMP/process/20220203
/hao/dawn/Data/UCoMP/process/20220207
/hao/dawn/Data/UCoMP/process/20220208
/hao/dawn/Data/UCoMP/process/20220214
/hao/dawn/Data/UCoMP/process/20220215
/hao/dawn/Data/UCoMP/process/20220216
/hao/dawn/Data/UCoMP/process/20220217
/hao/dawn/Data/UCoMP/process/20220218
/hao/dawn/Data/UCoMP/process/20220219
/hao/dawn/Data/UCoMP/process/20220220
/hao/dawn/Data/UCoMP/process/20220221
/hao/dawn/Data/UCoMP/process/20220223
/hao/dawn/Data/UCoMP/process/20220224
/hao/dawn/Data/UCoMP/process/20220225
/hao/dawn/Data/UCoMP/process/20220226
/hao/dawn/Data/UCoMP/process/20220227
/hao/dawn/Data/UCoMP/process/20220228
/hao/dawn/Data/UCoMP/process/20220301
/hao/dawn/Data/UCoMP/process/20220303
/hao/dawn/Data/UCoMP/process/20220304
/hao/dawn/Data/UCoMP/process/20220305
/hao/dawn/Data/UCoMP/process/20220313
/hao/dawn/Data/UCoMP/process/20220316
/hao/dawn/Data/UCoMP/process/20220319
/hao/dawn/Data/UCoMP/process/20220320
/hao/dawn/Data/UCoMP/process/20220321
/hao/dawn/Data/UCoMP/process/20220324
/hao/dawn/Data/UCoMP/process/20220325
/hao/dawn/Data/UCoMP/process/20220326

**Comment by mgalloy** [comment]
This is fixed in the 0.4.3 release.
