### ISSUE TITLE
Incorrectly named dark files

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#14]
`20210312.221426.48.ucomp.1083.l0.fts` is a dark (DARKSHUT is 'in' and DATATYPE is 'dark'), but has a `FILTER` value of '1083' and "1083" in the filename. This problem is also in `20210315.181801.34.ucomp.637.l0.fts`

**Comment by mgalloy** [comment]
Related, on 20210622, there were a bunch of dark files with a `FILTER` value (though the filename was correct):

    20210622.193002.79.ucomp.l0.fts         dark        530
    20210622.194433.14.ucomp.l0.fts         dark        637
    20210622.195842.63.ucomp.l0.fts         dark        656
    20210622.201252.33.ucomp.l0.fts         dark        691
    20210622.201729.22.ucomp.l0.fts         dark        706
    20210622.202207.10.ucomp.l0.fts         dark        789
    20210622.202646.24.ucomp.l0.fts         dark        1074
    20210622.203001.94.ucomp.l0.fts         dark        1079
    20210622.203317.51.ucomp.l0.fts         dark        1083
    20210622.204005.22.ucomp.l0.fts         dark        1083
    20210622.221648.50.ucomp.l0.fts         dark        1083
    20210622.221755.57.ucomp.l0.fts         dark        637
    20210622.221948.98.ucomp.l0.fts         dark        691
    20210622.222141.85.ucomp.l0.fts         dark        706
    20210622.222345.51.ucomp.l0.fts         dark        789
    20210622.222540.81.ucomp.l0.fts         dark        1074
    20210622.222743.83.ucomp.l0.fts         dark        1079
    20210622.222941.07.ucomp.l0.fts         dark        656
    20210622.223148.47.ucomp.l0.fts         dark        1083
    20210622.234050.44.ucomp.l0.fts         dark        789
    20210622.234154.48.ucomp.l0.fts         dark        637
    20210622.234347.91.ucomp.l0.fts         dark        691
    20210622.234540.76.ucomp.l0.fts         dark        706
    20210622.234734.47.ucomp.l0.fts         dark        789
    20210622.234929.86.ucomp.l0.fts         dark        1074

**Comment by bberkeyU** [comment]
Do we know if these were actually dark, the shutter was in the beam and
counts looked dark like?

I thought the code was always supposed to report the filter position, but
it would tag the DATATYPE and filename if the shutter was in the beam to
indicate that this file was dark.

Maybe I need a reminder of what is typically value for FILTER keyword for
dark images?

-Ben

**Comment by mgalloy** [comment]
It looks like a dark had either `FILTER` being the empty string or a random (whatever the last file had) wave region. Since a dark doesn't have a filter, I think it should have an undefined `FILTER`, i.e.:

    FILTER  =                      / [nm] Prefilter identifier

**Comment by bberkeyU** [comment]
We may have partially made this change to have filter act as you suggest;
but I thought at least for initial engineering we wanted to take darks with
multiple prefilters to check for light leaks and the filter keyword let's
us differentiate.
