### ISSUE TITLE
Determine waves and synoptic programs from OBS_PLAN

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#142]
All the unique `OBS_PLAN`'s as of now:

- `all_wavelenght_coronal.cbk`
- `all_coronal_7.ckb`
- `waves_1074_1hour.cbk`
- `all_wavelength_coronal.cbk`
- `sumtest-1074.cbk`
- `waves_1074_1hour.ckb`
- `poor-weather-coronal-with-flats.cbk`
- `new_wave_scan.cbk`
- `sumtest-1074.ckb`
- `691_Scan_coronal.ckb`

Which are synoptic, and which are waves? See [programs_names.cfg](https://github.com/NCAR/ucomp-pipeline/blob/master/resource/program_names.cfg) for the current list.

**Comment by bberkeyU** [comment]
Hi Mike:

These should be some flavor of synoptic:
all_wavelenght_coronal.cbk
all_coronal_7.ckb
all_wavelength_coronal.cbk
poor-weather-coronal-with-flats.cbk

These should be waves:
waves_1074_1hour.cbk
waves_1074_1hour.ckb

These should be engineering and not summed in.
sumtest-1074.cbk
new_wave_scan.cbk
sumtest-1074.ckb
691_Scan_coronal.ckb

**Comment by mgalloy** [comment]
20210922 has `sumtest-1074.cbk` and can be used for testing.

**Comment by mgalloy** [comment]
This worked for 20210922 now.
