### ISSUE TITLE
Add mask extension to FITS files

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#153]
Instead of masking, add a mask extensions to the FITS files.

- [x] level 1 is not currently masked
- [x] level 2 files should have a mask extension if not masking them
- [x] `l2/mask_noise` should be set to "NO" to add "Noise mask" extension
- [x] perform geometric mask of level 2 FITS
- [x] mask L2 quicklooks

> [!NOTE]
> **Time estimate**: Given the answers to the above questions, this shouldn't take long, 2-3 hours.

**Comment by detoma** [comment]
- Level 1 data are totally unmasked.

- The geometric mask (occulter  & post) will be applied to all level2 data. 
  How much shall we over-mask the occulter?  If we mask the outer fov, at what radius shall we start masking?

- We need to decide if and how to mask the levels 2 data for noise in the commissioning reprocessing. 

Users asked for less masking. We can mask the fit extensions for noise or leave all pixels unmasked and add an extension with a noise mask. The mask can be a binary mask(s) or a quality mask, i.e. the photon noise at each pixel. We do not need to have the final mask ready for commissioning (we can do the noise computation later) but need to decide on the format so Mike can set this up.

**Comment by mgalloy** [comment]
Added extension place and name to documentation for #154.
