### ISSUE TITLE
Documentation on web page

### ISSUE THREAD

**Issue by jburkepile** [NCAR/ucomp-pipeline#154]
Please list documents / info that we want to have on web page; added to tarball files downloaded by user and for publications.

- [x] put the current version in `resource/docs/ucomp-user-guide.v1.0.pdf`

> [!NOTE]
> **Time estimate**: Put time estimate here.

**Comment by bberkeyU** [comment]
What sections do we want to see in the short guide?  Something graphical like the ComP data guide https://mlso.hao.ucar.edu/CoMPL2DataGuide.pdf

-Intro to ucomp (I am thinking of the abstract for one of our UCoMP posters)
-Table of lines observed with ucomp
-Description of L2 files.  (We need to agree on what these are first) Quick_Invert, Mean/Median, Combined Dynamics/Polarization, etc.  Including extension names. 

Do we want to touch on L0 or L1? 
What is missing?

**Comment by mgalloy** [comment]
I think it would be cool to have a short guide that is designed by Don. Maybe just 1-2 pages that would give just the basic reason to use the data and the basics on how to use the data along with some nice images.

**Comment by jburkepile** [comment]
Agree with Mike's and Ben's comments. In addition to Ben's list I would add a description of the Level 1 files and a succinct list of the data processing steps with a link to the github pipeline pages. It would also be good to include a link to the UCoMP instrument page. Need to ask Steve what documents he wants to add to the instrument page.

We can note that more detailed documentation is in progress.

**Comment by bberkeyU** [comment]
https://docs.google.com/document/d/1Lt2b4gx6GR1Wq8z1B0ceQKB0-PBCdGUCmPIKeIOlHQ0/edit
