### ISSUE TITLE
Reprocess with version 0.5.x

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#156]
Reprocess the mission.

- What date should I start with? *2021-07-15 will be the first date of the mission now*
- Only quicklooks still? *Yes*
- Reprocess 2022 first.

Tasks:

- [x] clear dates before start date

#### 2021

- [x] July 2021
- [x] August 2021
- [x] September 2021
- [x] October 2021
- [x] November 2021
- [x] December 2021

#### 2022

- [x] January 2022
- [x] February 2022
- [x] March 2022
- [x] April 2022
- [x] May 2022
- [x] June 2022
- [x] July 2022
- [x] August 2022
- [x] September 2022
- [x] October 2022
- [x] November 2022

#### `UCOMP_LOADCT_RGB` crash

*Not sure why this date crashed. I simply re-ran the date and it processed without error.*

- [x] `20220303`

**Comment by mgalloy** [comment]
To clear all dates before the new start date:

    ucomp clearday -f production 20210526-20210715

**Comment by mgalloy** [comment]
Started the reprocessing with 2 processes on 6 machines (one is being used heavily already).

**Comment by mgalloy** [comment]
Current progress:

    ~$ ucomp versions -f production --summary 20210715-20221126
    --L--: 11 days
    -----: 1 day
    0.4.3: 349 days
    0.4.4: 1 day
    0.4.5: 1 day
    0.4.6: 18 days
    0.5.0: 24 days

**Comment by bberkeyU** [comment]
Mike, how should we make sense of this?

Are we expecting reprocessing to take 24 more days?  Or does this mean we
have finished or maybe started reprocessing 24 days?

-Ben

**Comment by mgalloy** [comment]
Currently, there are 24 days that are processed with the new version 0.5.0, 18 days with 0.4.6, 1 day with 0.4.5, etc. There are 11 "L=locked" days, which are currently being processed. And 1 day that doesn't have a version (maybe it is in between steps right now). I started about 4 hours ago, so that's about 6 days processed/hour. There are 405 total days to process (now that the mission starts on 20220715), so it should take about 67.5 hours (3 days). I don't think we can count on keeping that pace, but it is going smoothly so far.

**Comment by bberkeyU** [comment]
Thank you for the explanation.  Makes sense now.

**Comment by mgalloy** [comment]
Current status:

    --L--: 11 days
    -----: 2 days
    0.4.3: 300 days
    0.4.4: 1 day
    0.4.5: 1 day
    0.4.6: 15 days
    0.5.0: 75 days

**Comment by mgalloy** [comment]
Current progress:

    --L--: 14 days
    -----: 1 day
    0.4.3: 236 days
    0.4.4: 1 day
    0.4.6: 13 days
    0.5.0: 140 days

Current estimate of finish is Tuesday at 3 am.

**Comment by mgalloy** [comment]
Current progress:

    --L--: 12 days
    0.4.3: 202 days
    0.4.4: 1 day
    0.4.6: 12 days
    0.5.0: 178 days

Current estimate of finish is Tuesday at 5 am.

**Comment by mgalloy** [comment]
Current progress:

    --L--: 15 days
    0.4.3: 125 days
    0.4.6: 7 days
    0.5.0: 258 days

Current estimate of finish is Tuesday at 3 am.

**Comment by mgalloy** [comment]
Current progress:

    --L--: 13 days
    -----: 1 day
    0.4.3: 90 days
    0.4.6: 4 days
    0.5.0: 297 days

Current estimate of finish is Tuesday at 5 am.

**Comment by mgalloy** [comment]
It's done:

    0.5.0: 405 days
