### ISSUE TITLE
Create YYYYMMDD.ucomp.wavelength.l2.cookbook.{mean,median}.iquv.all data products

### ISSUE THREAD

**Issue by bberkeyU** [NCAR/ucomp-pipeline#158]
Along with `YYYYMMDD.ucomp.WWWW.l2.cookbook.{mean,median}.iquv` data products should the pipeline create `YYYYMMDD.ucomp.wavelength.l2.cookbook.{mean,median}.iquv.all` data products including the other wavelength tunings?

I don't know if these would be generally useful, but they would help me with something I am working on today.

> [!NOTE]
> **Time estimate**: This would take about 4-6 hours.

**Comment by mgalloy** [comment]
Here are some example images for 20220901:

![20220901 ucomp 1079 l1 synoptic mean iquv all](https://github.com/NCAR/ucomp-pipeline/assets/713524/3f274b18-6f94-4e8a-9e3d-b295153686ec)

![20220901 ucomp 1079 l1 synoptic median iquv all](https://github.com/NCAR/ucomp-pipeline/assets/713524/35b01428-287f-4bc8-9969-1d7f89db9276)
