### ISSUE TITLE
Change line width computation

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#160]
Use FWHM instead.

Change extension name and multiply by the correct constant.

This should just be multiplying our current line width by a constant, but I need the constants.

I need:

- [x] extension name: use "Line width (FWHM)"
- [x] plot annotation name: use "Line width (FWHM)"
- [x] constants for converting to FWHM
- [x] scale displays #157
- [x] change rest wavelength computation thresholds in `comp_l2_file`
- [x] move L2 noise thresholds to the wave region config files
- [x] make sure L2 line width noise threshold is in the correct units

> [!NOTE]
> **Time estimate**: Once I have the items listed above, this issue should be done in less than an hour.

**Comment by detoma** [comment]
Currently we use for line width the e-folding  W = 2 * sigma

We want to change to the FWHM = 2 * sqrt(2ln2)* sigma = 2.35482 * sigma

FWHM = sqrt(2ln2) * W = 1.7741 * W

To adjust the scaling in the plots of W, just multiply the current min and max values by 1.7741. 

Same for the where conditions that use W, e.g. in the level2 analytical code

**Comment by mgalloy** [comment]
Use "Line width (FWHM)" for extension name and GIF annotation.

**Comment by mgalloy** [comment]
Be careful using line width in thresholding conditions. Units for line width will stay in "km/s".

**Comment by mgalloy** [comment]
Check line width vs. Maurice's results.

**Comment by detoma** [comment]
I updated the line width factor. 

Steve please look it up. I think it is correct based on the definition of W used in equation (1) of the Hui Tian et al. 2013 paper.

There is a typo in equation (6) of Tian et al. 2013 paper but the COMP and UCOMP codes are correct and use :

W =  sqrt(-2.0 * d_lambda^2 / (a + b))

**Comment by detoma** [comment]
I just noticed that in the old COMP pipeline, we defined the line width as W/sqrt(2), i.e what we reported as line width was sigma. This seems different from what we did for UCOMP in the first data release. We need to compare codes and make sure we use consistent definitions when we reprocess COMP and UCOMP.

**Comment by mgalloy** [comment]
@detoma's comment above might change the threshold's we use for masking in the level 2.
