### ISSUE TITLE
Adjust d_lambda in level 2 analytic gaussian

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#165]
@detoma:

> Is there a reason why your d_lambda is 0.109985 instead of 0.11000?
>
> I thought the step in wavelength was 0.11 and earlier on 0.12. 
>
> Does this come from Steve?

> [!NOTE]
> **Time estimate**: I am not sure what exactly the request is for. I subtract the wavelengths of consecutive measurements to determine `d_lambda`. I could change it fairly easily though, so less than an hour if given a fixed or easily calculable number.

**Comment by bberkeyU** [comment]
The pipeline definition of d_lambda is (center wavelength)-(blue wavelength) for the three tunings closest to the nominal line position. Until now, most (outliers may be the >7 point scans looking for corona) of the wavelength spacings have been identical within a recipe file, so it shouldn't matter which tunings we use to calculate d_lambda.  

But there is no reason this has to be true, and if we go back to 5-point data, there is a strong possibility we will go to non-uniform spacing between the 5 points.  So we may want to revisit if we should save d_labda and what we want it to mean in a case where the spacing is non-uniform.  

Assuming this ticket was created in response to 3 points 1074 data.  The 0.109985 was probably a floating point calculation issue.  None of the recipes specify tunings to more than the hundreds of a nm.  In the pipeline, we might correct this by rounding the d_lambda value to the nearest .01s or .001s place.

**Comment by mgalloy** [comment]
The value of `d_lambda` should be reported to 4 decimal places.

**Comment by bberkeyU** [comment]
@detoma I forgot this from the call this morning; where did you get the 0.109985? I don't think I am seeing a place where we report it in the fits files.  Do we actually need to make this correction anywhere?

**Comment by mgalloy** [comment]
I don't see anywhere in the code where I output the `d_lambda` value. Maybe we should put it into the FITS header, though?

**Comment by detoma** [comment]
This may not be a bug. Let's just record d_lamba in the header and we can check if it is correct.

**Comment by mgalloy** [comment]
Add a `D_LAMBDA` FITS keyword in the primary header of dynamics and quick invert files with comment "wavelength spacing for Gaussian fit".

- Should this be an extension keyword for all extensions that use the Gaussian fit instead?
- What should the keyword name and comment be?

**Comment by detoma** [comment]
Yes, I would put it in the primary header. The keyword name looks good. The comment could simply be "wavelength spacing"
