### ISSUE TITLE
Plot UCoMP filter temperature vs. voltage for a fixed wavelength

### ISSUE THREAD

**Issue by jburkepile** [NCAR/ucomp-pipeline#18]
Create new UCoMP engineering product: filter temperature vs. voltage. To keep the plot simple, we start with a plot of the temperature and voltage of one specific LCVR (LCVR3) for a fixed wavelength (1074.7 nm).

Plot temperature vs voltage for one wavelength (1074.70 nm) over the course of an observing day:
- filter element temperature FITS keyword:  `T_LCVR3` (in primary header)
- wavelength FITS keyword: `WAVELNG` =  1074.70 nm (in extension header)
- tuning voltage FITS keyword: `V_LCVR3` (in extension header)

Temperatures should be close to 35 degrees C.

Voltages are under 10 volts. Check with Ben to find if these are ever negative.

**Comment by bberkeyU** [comment]
I believe voltages should range from 0-10V.  If we find something outside of this range I will try to review the interpolation code to understand what happend.
