### ISSUE TITLE
Rescale plots of occulter eccentricity

### ISSUE THREAD

**Issue by jburkepile** [NCAR/ucomp-pipeline#196]
Rescale mission and daily plots:

Please rescale both mission and daily occulter eccentricity plots using 0 to 0.25 for all wavelengths, and both cameras over the mission. Current mission plots are scaled from 0 to 1.0, which is too broad of a range to capture the details of the day-to-day variation. The daily plots are currently scaled from 0 to 0.1 which is not sufficient to capture the data, particularly starting in summer 2022 when the measured eccentricity increases, on average, for all lines. 

This work can be done after AGU; not a high priority.

**Comment by mgalloy** [comment]
Example of new daily plot:

![20220901 ucomp 1074 daily eccentricity](https://github.com/NCAR/ucomp-pipeline/assets/713524/018667a9-8e65-4e65-8f5d-5548c4ae3d4b)

Example of new mission plot:

![20220901 ucomp 1074 mission eccentricity](https://github.com/NCAR/ucomp-pipeline/assets/713524/c77abd43-1510-459f-bf0c-0cf57074c3fe)
