### ISSUE TITLE
L0 Wave offsets may be reported incorrectly.

### ISSUE THREAD

**Issue by bberkeyU** [NCAR/ucomp-pipeline#209]
Looking at the recorded values for the wavelength offsets in the header, I find they vary more than expected.   Here is a list of 1074 files in which the wave offset value differs from the previous file. 

Note that between 2021-09-23 and 2022-01-17, the values ping pong between 1.87 and 1.85.  But based on the values tracked in GitHub, they should be 1.87 from 2021-9-23->2022-1-17 when changed to 1.94.   We should see no reported values of 1.85

It is unclear if there is a bug in the reporting, and we were applying 1.87 during the whole period.  Or if the bug was related to reading the tuning files and the 1.85 was the actual applied offset.

20210624.175152  1074    1.74
20210713.171808  1074    1.66
20210714.222742  1074    1.82
20210923.180803  1074    1.87
20211127.221434  1074    1.85
20211129.181647  1074    1.87
20220111.225822  1074    1.85
20220112.000033  1074    1.87
20220117.184930  1074    1.94
20220118.181105  1074    1.97
20220126.024219  1074    1.95
20220126.033204  1074    1.97
20220129.181758  1074    1.95
20220129.190212  1074    1.97
20220130.222843  1074    1.95
20220130.233058  1074    1.97
20220210.181317  1074    1.99
20220223.230347  1074    1.96
20220223.231910  1074    1.99
20220224.223847  1074    1.96
20220224.230127  1074    1.99
20220227.003322  1074    1.96
20220227.004827  1074    1.99
20220228.185334  1074    1.96
20220228.191555  1074    1.99
20220413.171540  1074    2.03
20220614.165423  1074    2.07
20220915.173548  1074    2.11

**Comment by StevenTomczyk** [comment]
That is very strange. We certainly did not change them that often.

**Comment by bberkeyU** [comment]
Further investigation shows the reporting problem was with the FILENAME and FILTER keywords.

During the 2021-09-23 and 2022-01-17 period, all the files with a 1074.7 tuning continued WAVOFF =1.87 (the correct value). 
 The only files that contained 1.85 were created with a 1079 observing program.
