### ISSUE TITLE
Add citation file

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#22]
Add a citation file ([documentation]) to allow others to cite the pipeline code easily.

[documentation]: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files

**Comment by mgalloy** [comment]
I have a basic citation file now, but should add more contributors.

**Comment by mgalloy** [comment]
Also, should the pipeline software have it's own DOI?

**Comment by jburkepile** [comment]
If you think the pipeline should have a DOI, please go ahead and do that.

In terms of UCoMP contributors, you may already have these names; if not, please be sure to include:
Enrico Landi, Phil Oakley, Dennis Gallagher, Rob Graves, Scott Sewell, Patrick Zmarzly, and Zihao Yang,
