### ISSUE TITLE
LCVRELX header value reported in the wrong units

### ISSUE THREAD

**Issue by bberkeyU** [NCAR/ucomp-pipeline#220]
It looks like the L0 `LCVRELX` header value for `20220901.211529.36.ucomp.1074.l0.fts` is:

```
LCVRELX  =                0.300 / [ms] Delay after LCVR turning before data  
```

The correct value is 0.3 [s] (seconds). The `header_config.ini` for the real-time code has been fixed, so this problem should be corrected for future UCoMP data, but we will need an epoch for data taken before 2023, to change to change the comment from [ms] to [s].

**Comment by mgalloy** [comment]
This is now in seconds:

```
LCVRELX =                0.300 / [s] delay after LCVR turning before data
```

@bberkeyU Should that "turning" actually be "tuning"?

**Comment by StevenTomczyk** [comment]
Yes, it should be tuning.
