### ISSUE TITLE
Continuum keywords should not appear in the secondary L2 header extensions

### ISSUE THREAD

**Issue by bberkeyU** [NCAR/ucomp-pipeline#223]
`CONTOFF` and `CONTIN` appear identical across the L2 extensions and should be promoted to the primary header.

#### Tasks

- [x] remove `CONTOFF` from level 1 extension headers
- [x] promote `CONTIN` to primary header in level 1 files

**Comment by mgalloy** [comment]
It looks like `CONTOFF` appears in both the level 1 primary and extension headers, which should not happen.

**Comment by mgalloy** [comment]
`CONTIN` is the same across all extensions in a level 1 file:

```
level1$ ucomp cat -k CONTIN 20220915.201558.ucomp.1074.l1.p3.fts
  1  both
  2  both
  3  both
  4  both
  5  both
  6  both
```

**Comment by mgalloy** [comment]
This looks good to me. For the latest run of 20220915, I see in the primary header:

```
CONTOFF =              1.25625 / [nm] continuum offset
COMMENT Continuum can be "red", "blue", or "both": "both" gives equal weight to
COMMENT red and blue sides, "red" samples 90% red contimuum and 10% blue, "blue"
COMMENT samples 90% blue continuum and 10% red; the continuum position is offset
COMMENT from line center by the value of CONTOFF
CONTIN  = 'both    '           / [both/blue/red] location of continuum
```

and neither in the extension headers.
