### ISSUE TITLE
Recompute the recipe tunings

### ISSUE THREAD

**Issue by bberkeyU** [NCAR/ucomp-pipeline#247]
Based on feedback in the UCoMP workshop, we need to optimize our wavelength tunings for the 3 and 5 wavelengths.

Current recipes can be found in:
https://github.com/NCAR/ucomp-configuration/tree/main/Recipes

In the 2022 observing program, we called the following recipes:
1074_03wave_2beam_14sums_1_rep_BOTH.rcp  (waves)
   1074.59, 1074.70, 1074.81

Synoptic program
637_03wave_2beam_16sums_4rep_BOTH.rcp
    637.35,  637.40,  637.45
670_03wave_2beam_16sums_4rep_BOTH.rcp
    670.11, 670.16, 670.21
706_03wave_2beam_16sums_4rep_BLUE.rcp
    706.13, 706.20, 706.27
761_03wave_2beam_16sums_4rep_BOTH.rcp
    761.04, 761.10, 761.16
789_03wave_2beam_16sums_4rep_BOTH.rcp
    789.33, 789.40, 789.47
802_03wave_2beam_16sums_4rep_BOTH.rcp
    802.35, 802.41, 802.47
991_03wave_2beam_16sums_4rep_BOTH.rcp
    991.17,  991.26, 991.35
1074_03wave_2beam_16sums_4rep_BOTH.rcp
   1074.59, 1074.70, 1074.81
1079_03wave_2beam_16sums_4rep_BOTH.rcp
   1079.69,  1079.80,  1079.91

**GdT: for 1074 and 1079 see wavelength position below**
**The spacing for 637, 670, 706, 761, 789 look fine**
**There is no much signal in the two wings of 991 and 802 and 991 does not seem well centered.**

**Comment by detoma** [comment]
For the cross-calibration test during the eclipse, we will scan the line Fe XIII lines with 7 wavelength positions around the nominal line center at 1074.70 and 1079.80nm with a variable step of 0.06nm and 0.05nm, i.e.:

1074.54      1074.59      1074.64      1074.70      1074.76      1074.81      1074.86
 and
1079.64     1079.69      1079.74      1079.80      1079.86      1079.91       1079.96

**Comment by detoma** [comment]
For the 5-point synoptic program, we will use:

1074.54      1074.60      1074.70      1074.80      1074.86
and
1079.64      1079.70      1079.80      1079.90      1079.96

The wavelengths for 3-point program will not change:

1074.59      1074.70      1074.81
and
1079.69      1079.80      1079.91

**Comment by bberkeyU** [comment]
In our eclipse planning meetings, we talked about the following programs:

**Cross-calibration of FeXIII**: during the Texas totality, and again, if we know when CyroNRSP is observing
[1074-5pts, 1079-5pts, 1074-5pts, 1079-5pts] (closely spaced to line peak to get better S/N) during the eclipse in Texas, while DKIST is observing  
  (~16  minutes for sci images + ~8 minutes for flats = 25 to 30 minutes (with contingency) (Need to decide 5vs7)  
ABRIDGED VERSION: [1074-5pts, 1079-5pts] 1 pass only 
**Waves program** (1 hour) + 5 min for flats - only need to run once if skies are clear (Sarah asks if this should go first)
**Synoptic program other: [637-3pts, 706-3pts, 789-3pts]** (Consider adding the best of program 5 engineering tests look good) => 10 minutes + 10 minutes flats
Repeat the 5 coronal lines above (Program 1 abridged and Program 2) - once
If time allows: **The 4 new lines: 3 pts of 761 (SXII) and 991 (SVIII), 670 (NiXV), 802 (NiXV)**  12 minutes + 12 minutes with flats    The SXII 761 nm line has the best signal of the new lines. The other lines are faint … but a tiny bit brighter than FeXV 706 nm
Repeat the Program 1(abridged) and Program 2 coronal lines until the end of the day.


My understanding is that based on discussions with Alin we want to replace Program 1 5pts FeXIII program with 7 points.    If we do that when will we observe with 5 points?

**Comment by detoma** [comment]
Ben,
 The observing program was submitted to WHPI by Joan and is the one below.

During the eclipse we will observe 1074 and 1079 with 7-points for cross-calibration with DKIST. This has been decided and the wavelengths selected (see above).

We will observe with 5-points 1074 and 1079 during the synoptic program. 

Eclipse program: [1074-7pts, 1079-7pts, 1074-7pts, 1079-7pts]  + dark/flats
ABRIDGED VERSION  if weather is questionable:   [1074-7pts, 1079-7pts] 1 pass only  
Waves program:  [1074-3pts] ~1 hour + 5 min for dark/flats  [unless weather is unstable and we do not expect 1h of data]
Synoptic program: [637-3pts, 706-3pts, 789-3pts, 1074-5pts, 1079-5pts]  run twice + dark/flats
If time allows, Synoptic programs new lines:  [670-3pts, 761-3pts, 802-3pts, 991-3pts] + dark/flats
If time allows, repeat Synoptic program until the end of the day

**Comment by detoma** [comment]
Programs for April 1 (the first day we will be taking data) to search the lines have been decided based on the expected drift of the filter. The observing plan is the following:

Plan A : 1074 wide scan to visually find the line at these 9-wavelengths:  1074.04      1074.16      1074.28      1074.40      1074.52      1074.64      1074.76    1074.88   1075.00 

Plan B: If we fail to find the line in Plan A, run a set of 3  points blue and red, with increasing distance from the first set.  This will likely run while Ben is double checking the results from Plan A.

If everything fails and we are not sure the instrument was fully stable in temperature when we did the first scan, we will repeat  the original scan (Plan A).

If Ben finds the 1074 line, we will run a 7-points scan for 1074 and 1079 and then proceed to find  the other lines with 9-points scans as described below. Flats will be taken for each line but intermixed with the science data to save time to move the diffuser in and out, i.e. line flat flat line line flat flat line etc.  Ben will use the relationship between line offsets and the offset just found for 1074 to determine the predicted offsets for the other lines and move red and blue from there.
 
1074 narrow scan 7 points 4 repeats 16 sums, spacing = 0.06 nm
1079  narrow scan 7 points 4 repeats 16sums, spacing = 0.06 nm   
 (visual check of data)
789    narrow scan 9 points 4 repeats 16sums, spacing = 0.05 nm
637    narrow scan 9 points 4 repeats 16sums, spacing = 0.04 nm
706    narrow scan 9 points 4 repeats 16sums, spacing = 0.04 nm

If time allows, we will do a similar search for the 4 new lines:

991   narrow scan 9 points 4 repeats 16sums, spacing = 0.06 nm
802   narrow scan 9 points 4 repeats 16sums, spacing = 0.05 nm
761  narrow scan 9 points 4 repeats 16sums, spacing = 0.05 nm
670  narrow scan 9 points 4 repeats 16sums, spacing = 0.04 nm

**Comment by bberkeyU** [comment]
Conditions were cloudy during the eclipse.  Data were taken the day after the eclipse with the following program: 
https://github.com/NCAR/ucomp-configuration/blob/181f5093028c59adf44ef431ba3d974d867e5c24/Recipes/eclipseDayAfter.md
