### ISSUE TITLE
NUMSUM may vary across extensions

### ISSUE THREAD

**Issue by bberkeyU** [NCAR/ucomp-pipeline#25]
While recipes typically have 1 NUMSUM for all extensions we should not assume that is the case.

In  `ucomp_l1_average_data.pro` line 100 we divide the data by `file.numsum` which seems to be the `NUMSUM` form the first extension in a FITS file.  This will normally be the correct answer, but the real-time code does not guarantee this to be the case. I recommend using the NUMSUM from the extended fits header to correct an individual extension.

**Comment by bberkeyU** [comment]
I believe we currently apply the individual extension numsum to the flats and darks but apply the file.numsum (first extension) to the science data.

**Comment by mgalloy** [comment]
51aa0adee1fd3c04deb11ec9da102f56c8e77745 removes normalization from dark/flat creation since it now in all reading of UCoMP data.
