### ISSUE TITLE
Wavelength step size now smaller than L1 iquv.all.png titles 

### ISSUE THREAD

**Issue by bberkeyU** [NCAR/ucomp-pipeline#257]
With the eclipse line spacing, we started selecting wavelengths with a resolution of .001nm, but the iquv.all.png title displays still assume a resolution of .01nm.

For example, in 20240409.182654.ucomp.637.l1.p5.iquv.all.png, the 637.36 column has the value 637.365 in the fits header.   This caused a minor inconvenience when searching for all the extensions with the value 637.36.

Could we report wavelengths to the .001's?  Alternatively, report the title to the same number of significant digits reported in the fits header.

**Comment by mgalloy** [comment]
I am looking for other places that wavelengths are reported, but I haven't found any other places yet.

**Comment by mgalloy** [comment]
Here is an example `iquv.all` image:

![20240409 182226 ucomp 789 l1 p5 iquv all](https://github.com/NCAR/ucomp-pipeline/assets/713524/03e5f6cd-ed99-4a6f-906b-aea87ff120f5)

**Comment by mgalloy** [comment]
I am finding no other reporting of wavelengths, so no other place to change to 3 decimal places.
