### ISSUE TITLE
UComp_get_dmatrix do temp compensation correctly

### ISSUE THREAD

**Issue by bberkeyU** [NCAR/ucomp-pipeline#26]
UCoMP ucomp_get_dmatrix.pro line 26 should is:

    dmx = dmx_coefs[*, *, wave_region_index, 0] $
              + mod_temp * dmx_coefs[*, *, wave_region_index, **0**]
but should read:

    dmx = dmx_coefs[*, *, wave_region_index, 0] $
              + mod_temp * dmx_coefs[*, *, wave_region_index, **1**]

Where the mod_temp needs to be multiplied by the array in the second index on the 4th axis.    (Hopefully, this makes sense; the sentence seems very clunky but I can't figure how how to word this better)

**Comment by mgalloy** [comment]
This is fixed in d99d2e7c4639ea7551bcdbda555c1896d2146e55. There was also a problem of using the wrong wave region's demodulation coefficients.
