### ISSUE TITLE
UCoMP GBU seems to be failing for TU_LCVR when it shouldn't

### ISSUE THREAD

**Issue by bberkeyU** [NCAR/ucomp-pipeline#27]
A spot check was done for one of the FITS files to show the problem, but it appears this issue applies to all/most of the data files taken recently.

From the `20211107.ucomp.1074.gbu.log` we see the following:

    Filename                                 Reason
    20211107.192028.ucomp.1074.l1.5.fts           3
    ......
    GBU bitmask codes
    Code    Description
        1   at least two identical TU_LCVR{1,2,3,4,5} temperatures
        2   a temperature is outside the nominal range
        4   sequential extensions were acquired more than 10.00 secs apart

From the `20211107.192028` header we get the following temps:

    TU_RACK =               19.242 / [C] Computer Rack Temp Unfiltered              
    TU_LCVR1=               34.543 / [C] Lyot LCVR1 Temp Unfiltered                 
    TU_LCVR2=               34.493 / [C] Lyot LCVR2 Temp Unfiltered                 
    TU_LCVR3=               34.576 / [C] Lyot LCVR2 Temp Unfiltered                 
    TU_LNB1 =               34.569 / [C] LiNb1 Temp Unfiltered                      
    TU_MOD  =               27.901 / [C] Modulator Temp Unfiltered                  
    TU_LNB2 =               34.477 / [C] LiNb2 Temp Unfiltered                      
    TU_LCVR4=               34.449 / [C] Lyot LCVR4 Temp Unfiltered                 
    TU_LCVR5=               34.203 / [C] Lyot LCVR5 Temp Unfiltered                 
    TU_BASE =               30.789 / [C] Instrument Baseplate Temp Unfiltereed      
    T_C0ARR =                      / [C] Camera 0 Sensor array temp                 
    T_C0PCB =               27.000 / [C] Camera 0 PCB board temp                    
    T_C1ARR =                      / [C] Camera 1 Sensor array temp                 
    T_C1PCB =               26.500 / [C] Camera 1 PCB board temp    

Per `src/gbu/ucomp_gbu_check_identical_temps.pro` we should only see this reason when 2 of the TU_LCVR values are identical or different by less than .0001.   But all of the TU_LCVR values are different and the smallest difference is .033V.   

For some reason the camera ARR temps failed to get written to the file; so this should fail for Reason 2 not 3 (2+1).

**Comment by mgalloy** [comment]
This was fixed in dfe28d9d21210461766ad637c574877193d1a1cd.
