### ISSUE TITLE
Add variable name to warning/errors messages

### ISSUE THREAD

**Issue by bberkeyU** [NCAR/ucomp-pipeline#28]
Hi Mike,

It would be helpful to me if this type of error message included a variable name.

Example:

    % Variable: OCCLTR-X  is undefined: <UNDEFINED>.

    % Variable is undefined: <UNDEFINED>.
    % Execution halted at:  UCOMP_FILE::_INVENTORY  432 /home/mgalloy/production-pipeline/ucomp-pipeline/src/fileio/ucomp_file__define.pro
    %                       UCOMP_FILE::INIT  590 /home/mgalloy/production-pipeline/ucomp-pipeline/src/fileio/ucomp_file__define.pro
    %                       UCOMP_RUN::MAKE_RAW_INVENTORY   63 /home/mgalloy/production-pipeline/ucomp-pipeline/src/ucomp_run__define.pro
    %                       UCOMP_MAKE_RAW_INVENTORY   18 /home/mgalloy/production-pipeline/ucomp-pipeline/src/level1/ucomp_make_raw_inventory.pro
    %                       UCOMP_PIPELINE_STEP   34 /home/mgalloy/production-pipeline/ucomp-pipeline/src/utils/ucomp_pipeline_step.pro
    %                       UCOMP_EOD_STEPS    15 /home/mgalloy/production-pipeline/ucomp-pipeline/src/eod/ucomp_eod_steps.pro
    %                       UCOMP_EOD_WRAPPER  100 /home/mgalloy/production-pipeline/ucomp-pipeline/src/eod/ucomp_eod_wrapper.pro
    %                       $         

    /export/data1/Data/UCoMP/logs/20211111.ucomp.eod.log:

    20211111.192002 CRITICAL: UCOMP_EOD_WRAPPER: Stack trace for error

    Sent from /home/mgalloy/production-pipeline/ucomp-pipeline/src/utils/ucomp_crash_notification.pro (mgalloy@kodiak)

**Comment by mgalloy** [comment]
Unfortunately, this type of error is caused by an undefined variable in the IDL code.

    % Variable is undefined: <UNDEFINED>.

where the `<UNDEFINED>` variable was the expression

    ucomp_getpar(primary_header, 'OCCLTR-X')

There is no way for IDL to know what the name of the FITS variable being undefined that is causing the IDL variable to be undefined.

But, what I have for situations where I know the variable is a float, then I can return NaN instead of `!null` from `UCOMP_GETPAR`, so the code no reads:

    self.occulter_x = ucomp_getpar(primary_header, 'OCCLTR-X', /float)

**Comment by bberkeyU** [comment]
Thanks.

Is there an easy way to run make an inventory on Kodiak in near-real time through the day? 

I am thinking of setting up a cronjob that calls ucomp_make_raw_inventory.pro on all the fits files in kodiak:/data/ucomp/ucomp

**Comment by mgalloy** [comment]
This sounds like a job for the realtime pipeline, which I think should be started soon.
