### ISSUE TITLE
L0 headers

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#3]
Here are some changes for the L0 headers present in the `20181219` test data. In general, this is just following the guidelines in the [specification](https://docs.google.com/document/d/1VNo3TJubLP8GsNvKImxg5ClCV_yIbUATi3iFTcI56pw/edit).

#### General

- [ ] follow the order of the keywords specified in the [spec](https://docs.google.com/document/d/1VNo3TJubLP8GsNvKImxg5ClCV_yIbUATi3iFTcI56pw/edit)
- [x] string values are left-justified, numeric values are right justified -- with a space between either the "=" on the left or the "/" on the right
- [x] the "/" should be in position 31 (first character for a line is position 0) unless the value is too long, then a it should be a space after the value
- [x] units should be at the start of the comment, not the end
- [x] NaN values should not be shown; for example, instead of:

          T_LCVR1 =                'NaN' / Lyot LCVR1 Temp

     do:

          T_LCVR1 =                      / Lyot LCVR1 Temp

#### Primary headers

- [x] still need to add `DATE-OBS` and `DATATYPE` (with value "sci" or "cal")
- [x] `BSCALE`, `EXPTIME`, `O1FOCUS`, `CM1SENT`, `CAM1PCBT`, `CAM2SENT`, `CAM2PCBT` should be floats, not strings
- [x] `BZERO`, `OCCLTR-X`, `OCCLTR-Y`, and `NUMSUM` should be integers, not strings
- [x] there are two `OCCLTR-X` keywords and they both have "Occulter Y position" as a comment
- [x] "in"/"out"/"mid" should be lowercase in `OCCLTR`
- [x] comments for `INSTRUME`, `OBS_IDVE`, and `OBS_PLVE` are too long and are getting truncated
- [ ] remove `STAGEID` keyword
- [x] `TELESCOP` value should be "20 cm One Shot"
- [x] use mixed case in comments for `ORIGIN`, and `DARKID`
- [x] `INSTRUME` value should be 'UCoMP', comment 'Upgraded Coronal Multichannel Polarimeter'
- [x] `TCAMID` and `RCAMID` are not complete — it should be something like `OWL1280-10006`
- [x] remove comment for `OBSERVER`
- [x] `OPALID` should renamed to `DIFFSRID`, comment should be "Unique ID of diffuser used", and the value should be more specific (ask Steve for proper identifier)
- [x] `OBJECT` value should be "Sun" with comment "Corona or chromosphere"
- [x] add `DIFFSR` keyword with values "in"/"out"/"mid" with comment "Diffuser in or out of the beam"

#### Extension headers

- [ ] remove `FILTER` and `SEQNUM` keywords from extension header
- [x] `NUMSUM` should be integer, not string
- [x] `WAVELENG`, `LCVR?`, `SGS*`, `POLANGLE`, and `RETANGLE` (can't tell about `T_*` keywords since they were all NaNs, but them too) should be a floats, not strings
- [x] "wavelength" is misspelled in comment for `WAVELENG`
- [x] "V" for volts should be capitalized, it is in lowercase in some SGS keywords
- [x] give units for temperatures in `T_*`
- [x] `ONBAND` comment should give camera number, i.e., if value is 'RCAM', comment should be 'Camera 0 tuned to WAVELENG'
- [x] "in"/"out"/"mid" should be lowercase in `CALPOL`, `CALOPTIC`, and `DARKSHUT`
- [x] missing `COVER` keyword with values "in" or "out"

#### Questions

- [ ] How many digits of precision for each one of the floats? Whatever the hardware provides?
- [x] Does `NUMSUM` vary by extension? Should it be in the primary or extension header? It should not be in both.
- [x] Should we really have a "mid" value for in/out keywords?

**Comment by mgalloy** [comment]
For example, the primary header current looks like:
                                                        
    SIMPLE  =                    T / Conforms to FITS standard v3.0
    BITPIX  =                    8 / Character or unsigned binary integer
    NAXIS   =                    0
    EXTEND  =                    T / May contain conforming extensions
    ORIGIN  = 'NCAR/HAO' / INSTITUTION
    INSTRUME= 'Upgraded Coronal Multichannel Polarimeter' / Upgraded Coronal Multich
    TELESCOP= '20 CM One shot'
    LOCATION= 'MLSO'
    OBJECT  = 'Solar Corona'
    BZERO   = '0'
    BSCALE  = '1.0'
    LEVEL   = 'L0' / Level 0 (summed raw images)
    DARKID  = 'DARK SHUT 1' / DARK SHUTTER ID
    O1ID    = 'O1#1' / Unique ID of objective lens
    STAGEID = '10009,10106,10133,10294,10283' / STANDA STAGE SERAIL#
    OPALID  = 'OPAL2' / Unique ID of opal used (change to diffuser ID)
    OCCLTRID= '35' / Unique ID of the current occulter
    TCAMLUT = 'TCAM LUT 2018' / Unique ID of the LUT for TCAM
    RCAMLUT = 'RCAM LUT 2018' / Unique ID of the LUT for RCAM
    TCAMID  = '10006' / Unique ID of the Transmitted Camera
    RCAMID  = '10009' / Unique ID of the Reflected Camera
    OCCLTR  = 'Out' / Occulter Position in beam [in/out/mid]
    OBSERVER= 'MLSO' / Human on site
    EXPTIME = '85.00' / Exposure time [ms]
    OBS_ID  = 'header-demo' / Recipe descriptive name
    OBS_IDVE= '7379770593a3291baa0b4eed8ff5baeb' / Version of the recipe ID (MD5 has
    OBS_PLAN= 'header-demo.ckb' / Cookbook descriptive name
    OBS_PLVE= '0762e64b7cedb043e50a1e6cd11efdd2' / Version of the observing plan {co
    OBS_DESC= 'Example Recipe to show off new features.' / Description of the cplan
    FILTER  = '1074.00' / [nm] Prefilter identifier
    OCCLTR-X= '2.000' / Occulter Y position
    OCCLTR-X= '3.000' / Occulter Y position
    O1FOCUS = '5.32' / O1 focus position
    CAM1SENT= '8.931' / Camera 1 Sensor array temp
    CAM1PCBT= '45.000' / Camera 1 PCB board temp
    CAM2SENT= '0.566' / Camera 2 Sensor array temp
    CAM2PCBT= '44.000' / Camera 2 PCB board temp
    NUMSUM  = '5.00' / Number of camera reads summed together

But should look like:

    SIMPLE  =                    T / Conforms to FITS standard v3.0
    BITPIX  =                    8 / Character or unsigned binary integer
    NAXIS   =                    0
    EXTEND  =                    T / May contain conforming extensions
    ORIGIN  = 'NCAR/HAO'           / Institution
    INSTRUME= 'UCoMP'              / Upgraded Coronal Multichannel Polarimeter
    TELESCOP= '20 cm One shot'     /
    LOCATION= 'MLSO'               /
    OBJECT  = 'Solar Corona'       /
    BZERO   =                    0 /
    BSCALE  =                  1.0 /
    LEVEL   = 'L0'                 / Level 0 (summed raw images)
    DARKID  = 'DARK SHUT 1'        / Dark shutter ID
    O1ID    = 'O1#1'               / Unique ID of objective lens
    STAGEID = '10009,10106,10133,10294,10283' / Standa stage serial #
    OPALID  = 'OPAL2'              / Unique ID of diffuser used
    OCCLTRID= '35'                 / Unique ID of the current occulter
    TCAMLUT = 'TCAM LUT 2018'      / Unique ID of the LUT for TCAM
    RCAMLUT = 'RCAM LUT 2018'      / Unique ID of the LUT for RCAM
    TCAMID  = '10006'              / Unique ID of the Transmitted Camera
    RCAMID  = '10009'              / Unique ID of the Reflected Camera
    OCCLTR  = 'out'                / [in/out/mid] Occulter Position in beam
    OBSERVER= 'MLSO'               / Human on site
    EXPTIME =                85.00 / [ms] Exposure time
    OBS_ID  = 'header-demo'        / Recipe descriptive name
    OBS_IDVE= '7379770593a3291baa0b4eed8ff5baeb' / Version of the recipe ID (MD5 has
    OBS_PLAN= 'header-demo.ckb'    / Cookbook descriptive name
    OBS_PLVE= '0762e64b7cedb043e50a1e6cd11efdd2' / Version of the observing plan {co
    OBS_DESC= 'Example Recipe to show off new features.' / Description of the cplan
    FILTER  = '1074'               / [nm] Prefilter identifier
    OCCLTR-X=                2.000 / Occulter X position
    OCCLTR-Y=                3.000 / Occulter Y position
    O1FOCUS =                 5.32 / O1 focus position
    CAM1SENT=                8.931 / Camera 1 sensor array temp
    CAM1PCBT=               45.000 / Camera 1 PCB board temp
    CAM2SENT=                0.566 / Camera 2 sensor array temp
    CAM2PCBT=               44.000 / Camera 2 PCB board temp
    NUMSUM  =                    5 / Number of camera reads summed together

**Comment by bberkeyU** [comment]
ONBAND comment should give camera number, i.e., if value is 'RCAM', comment should be 'Camera 0 tuned to WAVELENG'

I thought the discussion on this topic was that we wanted to use R and TCAM here to match the way we refer to cameras other places in the header.  Seems wrong to add new names for cameras here.    I recommend editing the google dock and leaving this as is.   

 Silly question:"in 30 years who will remember that Camera 0 and TCAM are the same thing?"  Silly answer: :"hopefully no one since TCAM should map to Camera 1"

**Comment by bberkeyU** [comment]
remove STAGEID keyword

This was added with the philosophy of "if we can measure it and it could change we may want to know about it".     Are we not thinking that motion control is motion control?  And there

**Comment by bberkeyU** [comment]
How many digits of precision for each one of the floats? Whatever the hardware provides?

TBD.  header_config.ini has been updated to support limiting fictitious precision.

Keywords that are floats now have an X.y precision specification.  Where X is the total number of digits and y is the number after the decimal point.    Currently, X and y can only be single digit numbers since I don't think we measure anything that would need even 1/2 this precision.    I think the desired wavelength has the highest precision thing we measure or command and that is only   NNNN.nn (ie 1083.12)  leaving us a few orders of magnitude to get more precise before this becomes a problem.

**Comment by bberkeyU** [comment]
1/7/2019 Copy of the UCoMP Header_config_ini  (Annoyingly github won't let you drop .ini files here so the .txt was happened to get past the filters).
[header_config.ini.txt](https://github.com/NCAR/ucomp-pipeline/files/2743015/header_config.ini.txt)

Currently we support 2 types of keyword string and float.
Strings keywords now automatically support the if your less than 18 chars long be 18 chars wide in the fits header.  Or if you are longer be as long as you need.

Float keywords will either have the precision of whatever the labview fits writer wants or need to be specified as a 
floatX.y, where X and y are signle digit integers, describe the precision on either side of the decimal point.      (In the attached ini file everyone was changed to float5.3 as a starting point  but this should not be considered a good or final estimate for any one of the fits keywords).

**Comment by mgalloy** [comment]
In regards to the `ONBAND` keyword, it will always be necessary to know that `RCAM` is camera 0, i.e., that `im[*, *, *, 0]` represents RCAM.

**Comment by bberkeyU** [comment]
Sorry I read the request as the ONBAND value should have 0 or 1 in it.  But
I see that the change request was for ONBAND comment.   I have no issue
changing the comment.

**Comment by mgalloy** [comment]
@bberkeyU You mention above that there are currently only string or float keywords. What is the plan for integers? Some keywords need to be integers.

**Comment by bberkeyU** [comment]
@mgalloy  I think floatX.0 will produce a fits style int, so we don't need another keyword for that.

**Comment by mgalloy** [comment]
Issues and questions for the primary header for the new example file `20191009.152516.70565.ucomp.FTS` provided on November 14, 2019:

- [ ] `FILTER`, i.e., pre-filter identifier, should be a string, not a float.
- [ ] `NUMSUM` not present.
- [ ] `[TR]CAMLUT` values should be empty if there is not value.
- [ ] `DATE-END` not present.
- [ ] Order does not follow spec.
- [ ] `OBSSWID` not present.
- [ ] `EXPTIME` not present.
- [ ] `DATE-OBS` is reported to 5 decimal places in seconds. Is this necessary? Does the computer know the time to this accuracy?

Here is the primary header for reference:

    SIMPLE  =                    T / Conforms to FITS standard v3.0                  
    BITPIX  =                    8 / Character or unsigned binary integer           
    NAXIS   =                    0                                                  
    EXTEND  =                    T / May contain conforming extensions              
    ORIGIN  = 'NCAR/HAO'           / Institution                                    
    INSTRUME= 'UCoMP'              / Upgraded Coronal Multichannel Polarimeter      
    TELESCOP= '20 cm One shot'                                                      
    LOCATION= 'MLSO'                                                                
    OBJECT  = 'Solar Corona'       / Corona and Chromosphere                        
    BZERO   =                    0 / Zero point                                     
    BSCALE  =                    1 / Bit scale                                      
    LEVEL   = 'L0'                 / Level 0 (summed raw images)                    
    DARKID  = 'DARK SHUT 1'        / Dark Shutter ID                                
    O1ID    = 'O1#1'               / Unique ID of objective lens                    
    STAGEID = '10009,10106,10133,10294,10283' / Standa stage serial numbers         
    DIFFSRID= 'OPAL2'              / Unique ID of diffuser used (change to diffuser 
    OCCLTRID= '35'                 / Unique ID of the current occulter              
    TCAMLUT = 'No TCAM LUT'        / Unique ID of the LUT for TCAM                  
    RCAMLUT = 'No RCAM LUT'        / Unique ID of the LUT for RCAM                  
    DATE-OBS= '2019-10-09T15:25:16.70565' / UTC Date time when obs was started      
    DATATYPE= 'sci'                / [sci/cal] Science or Calibration               
    TCAMID  = 'Raptor OWL1280 10006' / Unique ID of the TCAM (Camera 1)             
    RCAMID  = 'Raptor OWL1280 10009' / Unique ID of the RCAM (Camera 0)             
    OCCLTR  = 'out'                / [in/out/mid] Occulter Position in beam         
    OBSERVER= 'MLSO'                                                                
    OBS_ID  = '1074_1beam_4sums'   / Name of current observation                    
    OBS_IDVE= 'e944a17bb0493e3817dc8c98dee37c3d' / [Md5 hash] Observation ver       
    OBS_PLAN= 'clock_polarizer.cbk' / Name of Current program                       
    OBS_PLVE= '814c6255904f095232ebfc05fb732322' / [Md5 hash] Program ver           
    OBS_DESC= ''                   / Description of the program                     
    FILTER  =                0.000 / [nm] Prefilter identifier                      
    OCCLTR-X=                2.000 / Occulter X position                            
    OCCLTR-Y=                3.000 / Occulter Y position                            
    O1FOCUS =                5.320 / O1 focus position                              
    CAM1SENT=               10.377 / Camera 1 Sensor array temp                     
    CAM1PCBT=               44.000 / Camera 1 PCB board temp                        
    CAM2SENT=                1.509 / Camera 2 Sensor array temp                     
    CAM2PCBT=               42.500 / Camera 2 PCB board temp

**Comment by bberkeyU** [comment]
NUMSUM not present.   Should be removed from the primary header spec it is meanless at this level.

 DATE-END not present.  I am not sure how to best capture this at L0.  
 Order does not follow spec.     Can the order in the spec be changed?  

 DATE-OBS is reported to 5 decimal places in seconds. Is this necessary? Does the computer know the time to this accuracy?  What accuracy do you want?

**Comment by mgalloy** [comment]
Issues and questions for the extension headers for the new example file 20191009.152516.70565.ucomp.FTS provided on November 14, 2019:

- [ ] `SGSLOOP` should be an integer, either 0 or 1.
- [ ] Is `T_LCVR6` no longer needed?
- [ ] Why are `T_LN[12]` and `TU_LN[12]` listed bewteen LCVR3 and LCVR4?
- [ ] `BODYTEMP`, `BASETEMP`, `RACKTEMP`, and `OPTRTEMP` not present? Are they represented in the other temperatures?
- [ ] `NUMSUM` and `EXPTIME` do not change per extension? Should they be in the primary extension?
- [ ] Comment for `EXTDATE` truncated.
- [ ] Comments for `NAXIS[1234]` should useful.
- [ ] `CONTIN` value should be lowercase, i.e., "both", not "BOTH".

Here is an extension header for reference:

XTENSION= 'IMAGE   '           / image extension                                
BITPIX  =                   16 / 16-bit two's complement binary integer         
NAXIS   =                    4                                                  
NAXIS1  =                 1280                                                  
NAXIS2  =                 1024                                                  
NAXIS3  =                    4                                                  
NAXIS4  =                    2                                                  
PCOUNT  =                    0                                                  
GCOUNT  =                    1                                                  
CALPOL  = 'in'                 / [in/out/mid] Position in beam                  
EXTDATE = '2019-10-09T15:25:16.70565' / Date time of the begining of data for th
WAVELNG =             1074.700 / [nm] Wavelength of observation                 
ONBAND  = 'TCAM'               / Camera tuned to WAVELNG                        
CONTIN  = 'BOTH'               / [both/blue/red] Location of the continum w.r.t.
O1ND    = 'out'                / [out/in/mid] Manual O1ND filter in beam        
NUMSUM  =                    4 / Number of camera reads summed together         
EXPTIME =                5.000 / [ms] Exposure time                             
FRAMERT =               52.632 / [Hz] Frequency of images                       
SEQNUM  =                    0 / Position number in the Observation             
CALOPTIC= 'in'                 / Polarizer and retarder in or out of the beam   
COVER   = 'out'                / [out/in/mid] O1 Lens cover                     
DIFFUSR = 'out'                / [out/in/mid] Diffuser                          
DARKSHUT= 'out'                / Dark shutter in or out of the beam             
POLANGLE=              170.000 / [deg] angle of rotation of cal polarizer       
RETANGLE=               30.000 / [deg] angle of rotation of cal retarder        
LCVR1   =               2.6567 / [V] Tuning Voltage                             
LCVR2   =               3.5313 / [V] Tuning Voltage                             
LCVR3   =               2.5747 / [V] Tuning Voltage                             
LCVR4   =               2.7244 / [V] Tuning Voltage                             
LCVR5   =               2.5392 / [V] Tuning Voltage                             
T_AIR   =              27.2198 / [C] Instrument Temp AIR                        
T_LCVR1 =              34.5110 / [C] Lyot LCVR1 Temp                            
T_LCVR2 =              34.4609 / [C] Lyot LCVR2 Temp                            
T_LCVR3 =              34.5589 / [C] Lyot LCVR3 Temp                            
T_LN1   =              34.5470 / [C] LN1 Temp                                   
T_LN2   =              34.4600 / [C] LN2 Temp                                   
T_LCVR4 =              34.4740 / [C] Lyot LCVR4 Temp                            
T_LCVR5 =              34.3260 / [C] Lyot LCVR5 Temp                            
TU_AIR  =               27.253 / [C] Instrument Temp AIR  Unfiltered            
TU_LCVR1=               34.511 / [C] Lyot LCVR1 Temp Unfiltered                 
TU_LCVR2=               34.460 / [C] Lyot LCVR2 Temp Unfiltered                 
TU_LCVR3=               34.558 / [C] Lyot LCVR2 Temp Unfiltered                 
TU_LN1  =               34.546 / [C] LN1 Temp Unfiltered                        
TU_LN2  =               34.460 / [C] LN2 Temp Unfiltered                        
TU_LCVR4=               34.474 / [C] Lyot LCVR4 Temp Unfiltered                 
TU_LCVR5=               34.326 / [C] Lyot LCVR5 Temp Unfiltered                 
SGSDIMM =                1.000 / [V] SGS Dim Mean                               
SGSDIMS =                2.000 / [V] SGS Dim Std                                
SGSSUMV =                3.000 / [V] SGS Sum Mean                               
SGSSUMS =                4.000 / [V] SGS Sum Std                                
SGSRAV  =                5.000 / [V] SGS RA Mean                                
SGSRAS  =                6.000 / [V] SGS RA Std                                 
SGSDECV =                7.000 / [V] SGS DEC Mean                               
SGSDECS =                8.000 / [V] SGS DEC Std                                
SGSLOOP =                9.000 / SGS Loop Fraction                              
SGSRAZR =                0.000 / [V] SGS RA zero point                          
SGSDECZR=                0.000 / [V] SGS DEC zero point

**Comment by bberkeyU** [comment]
EXPTIME not present.  This is also undefined at the primary header level and should be in the extended header.

**Comment by bberkeyU** [comment]
Comments for NAXIS[1234] should useful. What is the exact text that should come on with these?
Camera Number, Modulation Number, Array X, Array Y?

**Comment by bberkeyU** [comment]
Is T_LCVR6 no longer needed?  Yes there are only 5 LCVR's in the filter

**Comment by bberkeyU** [comment]
For 16bit unsigned images what should be the values for the following keywords:
BITPIX
BSCALE
BZERO 

I assumed BITPIX would be 16 and but I dont know the FITS SPEC well enough to know what  should BSCALE and BZERO be and weather these values belong in both the primary and extended headers. 

From the validator config it looks like the pipeline is expecting BITPIX=8
/home/mgalloy/projects/ucomp-pipeline/src/validate/ucomp.l0.validation.cfg says BITPIX should be 
BITPIX   : required, value=8, type=int

**Comment by mgalloy** [comment]
OK, I changed the spec for `BITPIX` to 16. I believe `BZERO` should then be 32768 and `BSCALE` stays at 1.0.

**Comment by bberkeyU** [comment]
Do these values belong in the primary header extended header or both?    For ucomp there will be no image data in the primary header.

**Comment by mgalloy** [comment]
They should be as we discussed in the extension header. I think normally you have to put some placeholder value in the primary header, like a scalar 0, so `BITPIX`, `BZERO`, and `BSCALE` should be set appropriately for whatever is actually there.

**Comment by bberkeyU** [comment]
Mike, is this issue still relevant?  THe last comment was 3 years ago.

**Comment by mgalloy** [comment]
I think we are probably good now.
