### ISSUE TITLE
UCoMP L1 headers

### ISSUE THREAD

**Issue by bberkeyU** [NCAR/ucomp-pipeline#39]
Looking at `20220203.205119.ucomp.1074.l1.3.fts` reprocessed April 7th:

    DATE_DP = '2022-04-07T18:31:55' / L1 processing date/time [UTC]                 
    DPSWID  = '0.2.35 [df5ded6]'   / L1 processing software (2022-04-05) [production

I see a lot of information in the extended headers that shouldn't be there.  For L1, the extensions should only have data specific to I, Q, U, or V data with common data going into the primary header.  Right now, I think we just have a copy of the L0 extended headers, and we are getting things like `DARKSHUT`, `DIFFUSR`, and `SGS`.  Most of this probally shouldn't be in the L1 headers since a Q L1 image has multiple, darks, coronal and flat images mixed into it.

I came across this issue because I was looking for SGS data, but I am now realizing that at least for what I wanted the SGS data for it doesn't make sense to get it from the L1 files and it might not make sense to include it in L1 at all. From the guider, the SGS data is valid over a 15-second window but the L1 files contain coronal data over a ~2-minute window.  So if we include SGS we will either have to figure how how to pick a representative value or combine together all the values in an average or median-like operation.

**Comment by mgalloy** [comment]
I would definitely like to have feedback on the L1 headers. Currently, Steve's pipeline also keeps `DARKSHUT`, `DIFFUSR` and the `SGS` keywords. I added this topic to the agenda for next week's UCoMP pipeline meeting. We need to go over the entire L1 header thoroughly before we release the data to the public.

**Comment by bberkeyU** [comment]
Draft recommendations:
https://docs.google.com/document/d/1e7PthNUe75aBnWX8a3iI9HX8cinZa1SPlCB3VuzCFhU/edit?usp=sharing

**Comment by bberkeyU** [comment]
Document moved to a shared drive. It is now:
https://docs.google.com/document/d/1e7PthNUe75aBnWX8a3iI9HX8cinZa1SPlCB3VuzCFhU/edit?usp=sharing

**Comment by bberkeyU** [comment]
Please feel free to edit the L1 fits header recommendation file (linked above).

**Comment by mgalloy** [comment]
Here are corrections to make to the level 1 header:

- [ ] average SGS values every time extensions are combined
- [ ] add `SECANT_Z` keyword
- [ ] add `CRPIX{1,2}` and `CRVAL{1,2}` keywrods
- [ ] remove `SEQNUM` keyword
- [ ] remove hardware position keywords
- [ ] promote keywords that should not change per extension to the primary header: `FRAMERT`, `EXPTIME`

**Comment by mgalloy** [comment]
Here is Steve's current level 1 extension header:

    XTENSION= 'IMAGE   '           /extension type
    BITPIX  =                  -32 /bits per data value
    NAXIS   =                    3 /number of axes
    NAXIS1  =                 1280 /
    NAXIS2  =                 1024 /
    NAXIS3  =                    4 /
    PCOUNT  =                    0 /
    GCOUNT  =                    1 /
    EXTNAME = 'sci [ 637.35 nm]'   /
    O1FOCUS =               22.330 / O1 focus position
    DATATYPE= 'sci'                / [sci/cal/dark/flat] Science or Calibration
    DATE-BEG= '2022-04-10T17:17:42.94' / Date time of the beginning of data for this
    OBJECT  = 'SUN'                / Emission Line Corona
    WAVELNG =              637.350 / [nm] WAVELENGTH OF OBS
    O1ND    = 'out'                / [out/in/mid] Manual O1ND filter in beam
    EXPTIME =               80.000 / [ms] Exposure time
    FRAMERT =               10.691 / [Hz] Frequency of images
    SEQNUM  =                   23 / Position number in the Observation
    OCCLTR  = 'in'                 / [in/out/mid] Occulter Position in beam
    CALOPTIC= 'out'                / Polarizer and retarder in or out of the beam
    COVER   = 'out'                / [out/in/mid] O1 Lens cover
    DIFFUSR = 'out'                / [out/in/mid] Diffuser
    DARKSHUT= 'out'                / Dark shutter in or out of the beam
    POLANGLE=             -110.210 / [deg] angle of rotation of cal polarizer
    RETANGLE=              -86.940 / [deg] angle of rotation of cal retarder
    END

which according to the rules above should get down to:

    XTENSION= 'IMAGE   '           /extension type
    BITPIX  =                  -32 /bits per data value
    NAXIS   =                    3 /number of axes
    NAXIS1  =                 1280 /
    NAXIS2  =                 1024 /
    NAXIS3  =                    4 /
    PCOUNT  =                    0 /
    GCOUNT  =                    1 /
    EXTNAME = 'sci [ 637.35 nm]'   /
    O1FOCUS =               22.330 / O1 focus position
    DATATYPE= 'sci'                / [sci/cal/dark/flat] Science or Calibration
    DATE-BEG= '2022-04-10T17:17:42.94' / Date time of the beginning of data for this
    OBJECT  = 'SUN'                / Emission Line Corona
    WAVELNG =              637.350 / [nm] WAVELENGTH OF OBS
    O1ND    = 'out'                / [out/in/mid] Manual O1ND filter in beam
    END

**Comment by mgalloy** [comment]
The equation for calculating `SECANT_Z` from Steve is:

    secz = 1.d0/(sin(lat)*sin(sol_dec)+cos(lat)*cos(sol_dec)*cos(ha))

| I think the true declination. ha is the hour angle.

**Comment by mgalloy** [comment]
Finished work on specific tasks in this issue. Further work is done in #94.
