### ISSUE TITLE
L0 filename

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#4]
The raw filename should be `YYYYMMDD.HHMMSS.ucomp.l0.fts` where the date is specified in UT.

Might change `l0` to `l0mean` or `l0ave` at some point.

**Comment by bberkeyU** [comment]
Right now the code supports different number of sums/avgs/means/integrations for each extended header.    So there is no obvious mean value to plunk into the file names.

**Comment by mgalloy** [comment]
Example file given on November 14, 2019 is named `20191009.152516.70565.ucomp.FTS`. Is there a reason for the 5 decimal place accuracy of the seconds? Will there ever be any files written in the same second? Also, `FTS` extension should be lowercase.

**Comment by bberkeyU** [comment]
The system can (and has) taken data at a rate of more than once a second.    The 5 decimal places was just a too big to fail number it can be reduced.  

Can you remind me what 10 means?   Is this something related to wavelengths?
