### ISSUE TITLE
Add backgrounds to FITS file

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#46]
Add background image for each wavelength to the level 1 FITS file. So the number of extensions would double. If there are 3 wavelengths for the file, there would be 3 coronal image extensions sized `[1280, 1024, 4]` with name "Corona Stokes IQUV", then 3 background extensions sized `[1280, 1024]` with name "Background I".

**Comment by bberkeyU** [comment]
The plan is to structure the L1 3 wavelength fits headers like the following:

But with names Corona IQUV [ 1074.7 nm]   and Background [1074.7 nm]  for the central wavelength. 

![image](https://user-images.githubusercontent.com/22605316/220784264-aa4d54a7-0862-4000-bb23-26ec1dfc4160.png)
