### ISSUE TITLE
Files marked with incorrect wave region

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#54]
The following files have `FILTER` keyword set to "1074" and contain "1074" in the filename, but are 1079 files:

- [x] 20220111.225822.80.ucomp.1074.l0.fts
- [x] 20220111.230236.34.ucomp.1074.l0.fts
- [x] 20220111.230649.79.ucomp.1074.l0.fts
- [x] 20220111.231103.36.ucomp.1074.l0.fts
- [x] 20220126.024219.79.ucomp.1074.l0.fts
- [x] 20220130.222843.10.ucomp.1074.l0.fts
- [x] 20220130.223257.00.ucomp.1074.l0.fts
- [x] 20220130.223711.25.ucomp.1074.l0.fts
- [x] 20220130.224125.21.ucomp.1074.l0.fts
- [x] 20220223.230347.39.ucomp.1074.l0.fts
- [x] 20220223.230619.73.ucomp.1074.l0.fts
- [x] 20220224.223847.58.ucomp.1074.l0.fts
- [x] 20220224.224119.71.ucomp.1074.l0.fts
- [x] 20220227.003322.77.ucomp.1074.l0.fts
- [x] 20220228.185334.46.ucomp.1074.l0.fts
- [x] 20220228.185606.79.ucomp.1074.l0.fts
- [x] 20220301.180725.03.ucomp.1074.l0.fts
- [x] 20220301.180957.19.ucomp.1074.l0.fts
- [x] 20220301.214250.50.ucomp.1074.l0.fts
- [x] 20220301.214522.85.ucomp.1074.l0.fts

The following files have `FILTER` set to "637" and contain "637" in the filename, but are 706 files:

- [x] 20220311.174303.17.ucomp.637.l0.fts
- [x] 20220311.174535.33.ucomp.637.l0.fts
- [x] 20220324.174611.06.ucomp.637.l0.fts
- [x] 20220324.174843.60.ucomp.637.l0.fts

The following files have `FILTER` set to "789" and contain "789" in the filename, but are actually 1074 files:

- [x] 20220306.233111.88.ucomp.789.l0.fts
- [x] 20220306.233344.01.ucomp.789.l0.fts

Should the level 1 pipeline fix this issue? mark the file as invalid?

**Comment by bberkeyU** [comment]
It looks like the pipeline (On kodiak) didnt produce gifs for the 20220111 data with the bad wave regions.  Did the dawn pipeline produce gifs for these?  If now could we force the pipeline to produce them?  I would like to compare the 1074 and 1079 images for the day to better understand if these are actually completely valid 1079 images with the wrong file name or if the filterwheel (or something else) is setup for 1074.

Based on a quick 

 20220111.225822.80.ucomp.1074.l0.fts
 20220111.230236.34.ucomp.1074.l0.fts
 20220111.230649.79.ucomp.1074.l0.fts
 20220111.231103.36.ucomp.1074.l0.fts

**Comment by mgalloy** [comment]
I changed the raw files from filenames and FILTER keywords of "1074" to "1079" for four files on 20220111:

    20220111.225822.80.ucomp.1074.l0.fts
    20220111.230236.34.ucomp.1074.l0.fts
    20220111.230649.79.ucomp.1074.l0.fts
    20220111.231103.36.ucomp.1074.l0.fts

to

    20220111.225822.80.ucomp.1079.l0.fts
    20220111.230236.34.ucomp.1079.l0.fts
    20220111.230649.79.ucomp.1079.l0.fts
    20220111.231103.36.ucomp.1079.l0.fts

Results are in:

    /hao/dawn/Data/UCoMP/process.filterfix/20220111/

I gave a cursory look and it seems like that fixes it
