### ISSUE TITLE
Add O1ID to UCoMP database

### ISSUE THREAD

**Issue by bberkeyU** [NCAR/ucomp-pipeline#78]
Can you get the primary header `O1ID` added to the database so we can track changes against the O1? I am not sure the best location for this; it looks like the only place we are putting hardware ID's in the cals; but that doesn't seem like the best place to point hardware ID's since we dont run cals every day.

**Comment by mgalloy** [comment]
The right place would probably be the `ucomp_eng` table. The occulter ID is already there. I can add the `O1ID`.
