### ISSUE TITLE
Create false color temperature images

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#81]
Create two false color images per day (R-G-B):

- 706-1074-789
- 1074-789-637

Requirements:
- The component images should take center wavelength from the average file for the day. For 1074, use the waves average.
- The images should be placed in the `fullres` directory.

Annotations:
- upper left: "MLSO UCoMP Daily Temperature Image\n[DATE]"
- upper right: for 706-1074-789:

       Corona hottest in regions colored white or red
       Corona coolest in regions colored blue

   for 1074-789-637:

       Corona coolest in regions colored blue

- lower left: for 706-1074-789:

      RED = 706 mm FeXV log Teff=6.20-6.63
      GREEN = 1074 mm FexIll log Teff=6.08-6.41
      BLUE = 789 mm FeXl log Teff=5.92-6.30
      Where Teff=Effective Temperature

   for 1074-789-637:

       RED 1074 nm FeXIll log Teff=6.08-6.41
       GREEN = 789 mm FeXl log Teff=5.92-6.30
       BLUE = 637 nm FeX log Teff=5.80-6.24
       Where Teff=Effective Temperature

**Comment by mgalloy** [comment]
From @jburkepile:

#### Occulter sizes:

I made scans of the UCoMP occulter radius in different wavelengths in IDL and here is what I got:

- 1074 nm   occulter radius = 346.5 pixels
- 789 nm occulter radius = 339.5 pixels   (harder to measure due to low signal-to-noise)
- 706 nm occulter radius = 340.5 pixels
- 637 nm occulter = 334.5 pixels

From the ballpark measurements I made in IDL for the occulter radii I get:

- 789 radius = 0.9798  * radius of 1074
- 706 radius = 0.9827 * radius of 1074  
- 637 radius = 0.9657 * radius of 1074 

#### Unsharp Mask:

    img637 = unsharp_mask(img637, radius=5, amount=1)
    img1074 = unsharp_mask(img1074, radius=5, amount=4)
    img789 = unsharp_mask(img789, radius=5, amount=4)

I do not apply anything to 706. It enhances the noise as much as the corona (in my opinion).

#### Intensity scaling:

Cooler line image:

    tv, bytscl(img1074^0.5, 0, 10)
    tv, bytscl(img789(12:1291, 10:1033)^0.5, 0, 7)
    tv, bytscl(img637(23:1302, 18:1041)^0.5, 0, 5)

Hotter line image:

    tv, bytscl(img706(11:1290, 11:1035)^0.5, 0.2, 3.0)  

FOR 706: need to write mask occulter in 706 to block out unwanted scattered light:

    tvcircle, 340, 639, 510, 0, /fill

    tv, bytscl(img1074^0.5, 0, 10)
    tv, bytscl(img789(12:1291, 10:1033)^0.5, 0, 7)

**Comment by mgalloy** [comment]
We also need a way to create temperature maps over the day, and hence movies.

**Comment by jburkepile** [comment]
Mike:
The 637 does have enough signal to perform an unsharp mask. ... you just want to set the amount = 1. 
The line that doesn't have enough signal-to-noise is the 706. Don't use unsharp mask on 706.
For the 1074 and 789 lines you can set the amount = 4

I use radius = 5 for 637, 789 and 1074.
thanks!

**Comment by mgalloy** [comment]
I wrote the wrong thing in the comment above, but the code is correct. It enhances the other lines, but not 706 nm.
