### ISSUE TITLE
Eliminate bad frames

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#89]
Find a robust condition to eliminate bad frames, i.e., a single polarization state in a single extension, during the `UCOMP_L1_AVERAGE_DATA` step.

- [x] decide on format of storing the list of bad frames
- [x] store location of bad frames information in config file
- [x] read/retrieve bad frames when starting a day
- [x] pass bad frames to eliminate bad frames when reading the data in `UCOMP_RAW_DATA`
- [x] average over NaNs in `UCOMP_L1_AVERAGE_DATA`
- [x] report the bad frames in the level 1 file

**Comment by bberkeyU** [comment]
When combining like images, there should be a way to provide the pipeline with a list of bad images to be ignored.  This list could come on a manually produced epoch file or some preprocessing GBU-like step details tbd.

When combining like images, the pipeline should reject the bad image and use the mean of the remaining good images. 

If the number of good images for a particular type drops to 0, processing that entire fits file should stop.   As from that point on, we would be missing an entire modulation state for one of the coronal/continuum wavelengths tunings.  

A list of rejected images sighting the extension and modulation number should be reported in the L0 header.  For the L1 and L2 headers, we may want to produce a derived data product keyword that explains the type of data product that is affected and not just the extension number.  For example, in L1 if an L0 Extension 2 modulation  1 was rejected; a scientist would need to track the recipe to know which wavelength this is related to; so it would be nice if we reported something like "%Wave% wavelength, %coronal | continuum% image processed missing %x% frames"

**Comment by bberkeyU** [comment]
I created a new branch on GitHub called badExtension to try and capture how we could implement this issue.   The idea is to list bad cameras/extensions/modulations to ucomp_l1_average_data.pro; we then set the values in the bad image array to NAN's and then take the groupby mean with the /nan switch.    This will average together the good frames skipping anything marked bad.

We will probally get into some error condition if we mark all the frames in a group as bad (NAN); so more work will need to be done to get the pipeline to bail out of the process if a flavor of data is missing.

I expect the pipeline to ingest a bad frame file in the inventory step, but I don't have any suggestions for implementation details.  I expect the bad frames file will have a format similar to the following:
Filename, camera #, extension #, modulation # 

Should this be one file for the mission stored with the pipeline config, or should this be stored in the L0 data by date?
With the March bad Tcam cables, we had at least 80 bad frames.  We know we have some more bad frames in June/July 2020, so it seems likely we will have hundreds of bad frames over the UCoMP mission.

**Comment by mgalloy** [comment]
Here is an example file of bad frames for `20220310`:

    20220301.201005.14.ucomp.1074.l0.fts,1,2,2
    20220310.180408.94.ucomp.1074.l0.fts,1,8,3
    20220310.180408.94.ucomp.1074.l0.fts,1,15,3
    20220310.180408.94.ucomp.1074.l0.fts,1,19,2
    20220310.180926.43.ucomp.1079.l0.fts,1,4,1
    20220310.180926.43.ucomp.1079.l0.fts,1,5,0
    20220310.180926.43.ucomp.1079.l0.fts,1,7,0
    20220310.185936.79.ucomp.1074.l0.fts,1,3,3
    20220310.185936.79.ucomp.1074.l0.fts,1,3,3
    20220310.194057.04.ucomp.1074.l0.fts,1,1,0
    20220310.195208.65.ucomp.1074.l0.fts,1,5,0
    20220310.200354.12.ucomp.1074.l0.fts,1,2,3
    20220310.200822.76.ucomp.1074.l0.fts,1,5,3
    20220310.201003.45.ucomp.1074.l0.fts,1,2,2

[20220310.ucomp.badframes.csv](https://github.com/NCAR/ucomp-pipeline/files/11367300/20220310.ucomp.badframes.csv)

**Comment by mgalloy** [comment]
The bad frames information could be stored in various locations:

- in the `raw`/`incoming` directory for the date
- in a database
- in another location specified by the configuration file

Since the bad frames file would be determined well after the level 0 data is tarred and sent to the the archive, it would not be part of the level 0 tarball. Placing it in the `raw`/`incoming` directory would be potentially misleading then.

A database would be a fast and easy way to store the information, but would require a database connection for the run. If possible, it would be good to not require this.

A location specified by the configuration file is easy as well. We can add files to this location as needed, and these files can be rsync'ed to a backup location to preserve them. This seems the most reasonable method of storing the files of the format described in the above comment.

**Comment by mgalloy** [comment]
I can eliminate bad frames in the pipeline given a listing of the frames to ignore. For example, for 20220310.180408, previously:

![20220310 180408 ucomp 1074 l1 3 iquv old](https://user-images.githubusercontent.com/713524/236972091-25702258-56d6-4bae-973e-39efebd12207.png)

and now:

![20220310 180408 ucomp 1074 l1 3 iquv](https://user-images.githubusercontent.com/713524/236972111-990df378-4dff-409f-8678-0f8c50f1e893.png)

Still missing some bad frames for non-center wavelengths. Previously:

![20220310 180408 ucomp 1074 l1 3 iquv all old](https://user-images.githubusercontent.com/713524/236972156-ad856a51-4fb6-4006-9ce5-c740b1f6ae28.png)

and now:

![20220310 180408 ucomp 1074 l1 3 iquv all](https://user-images.githubusercontent.com/713524/236972176-595c883b-9e49-48e5-b29a-4db5da26597f.png)

It is now a matter of finding and listing all the bad frames for each image.

**Comment by mgalloy** [comment]
Updated bad frames for 20220310.180408:

![20220310 180408 ucomp 1074 l1 3 iquv all](https://github.com/NCAR/ucomp-pipeline/assets/713524/a68c2533-79c8-40b2-9d67-12ebb14174f8)

**Comment by mgalloy** [comment]
I still need a way to report the bad frames in a given FITS file. For the example file at 20220310.180408, there were 5 bad frames out of 192.

- Should this change the `NREPEAT` FITS keyword value? Currently, it is a scalar in the primary header. To change it for the bad frames would require it to be moved to the extension header and hold 8 values instead of a single value.
- Maybe the number of bad frames for the file should be reported? i.e., BADFRAME=5 for the 20220310.180408 image. There could be a comment that lists the camera, extension, pol state of the bad frames.

Maybe there is another way to report this?

**Comment by bberkeyU** [comment]
I don't think NREPEAT makes sense after we do the demodulation matrix
(especially if we want to track back frames to the L2 daily averages).  At
demodulation, we have 4 polarization images, each potentially with their
own value of NREPEAT;  for example, if ModulationA[NREPEAT] = 4
ModulationB[NREPEAT] = 3  ModulationC[NREPEAT] = 4  ModulationD[NREPEAT] =
2   there is no obvious NREPEAT to choose.

Let's figure out a way to list the bad frames in the header.  Or add a fits
table after the image extensions containing a list of bad frames by,
extension, camera, and modulation.

**Comment by mgalloy** [comment]
@bberkeyU Row 20 of the spreadsheet is:

    20220310.194740.07.ucomp.1074.l0.fts,2,6,0

I assume camera should be 1? Since this is a spreadsheet of TCAM bad frames?

**Comment by mgalloy** [comment]
I am using `NFRAME` and `REMFRAME` to record the frames in the file:

    NFRAME  =                  192 / total number of image frames in file
    REMFRAME=                    5 / number of bad frames removed

**Comment by mgalloy** [comment]
I could also use removed frames as a GBU condition.

**Comment by mgalloy** [comment]
`NFRAME` and `REMFRAME` are reported in the primary header.
