### ISSUE TITLE
Finalize level 1 headers

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#94]
Finalize the naming of extensions and the keywords in both the primary and extension headers.

- [x] finalize extension names
- [x] questions on the [this comment](https://github.com/NCAR/ucomp-pipeline/issues/94#issuecomment-1633269699) below
- [x] `HISTORY` keyword with level 1 processing steps
- [x] add `CONTOFF` keyword after `CONTIN` with comment "[nm] distance from WAVELNG for continuum wavelength"
- [x] move `BOPAL` and `BUNIT` to primary header
- [x] average SGS values into the primary header
- [x] remove `O1ND` from extension headers
- [x] add comment below `CONTIN` keyword (see below for text)
- [x] change `CONTIN` comment to "[both/blue/red] location of continuum"
- [x] change comment of `WAVELNG` to "[nm] Wavelength of emission line"
- [x] change `OBJECT` comment to "continuum emission" for background extension headers
- [x] check `O1FOCUS` is identical in extension headers, remove `O1FOCUSE` from primary header, promote `O1FOCUS` to primary header

Comment for below `CONTIN`:

    COMMENT Continuum can be [red,blue,both] BOTH gives equal weight to RED and BLUE sides
    COMMENT RED measures the continuum on the RED side of the WAVELNG by CONTOFF 
    COMMENT BLUE measures the continuum on the BLUE side of the WAVELNG by CONTOFF 

#### Extension names

For the pipeline:

    Corona Stokes IQUV [1074.59 nm]
    Corona Stokes IQUV [1074.70 nm]
    Corona Stokes IQUV [1074.81 nm]
    Background I [1074.59 nm]
    Background I [1074.70 nm]
    Background I [1074.81 nm]

For Steve's pipeline:

    Corona IQUV[1074.59 nm]
    Corona IQUV[1074.70 nm]
    Corona IQUV[1074.81 nm]
    Background I[1074.59 nm]
    Background I[1074.70 nm]
    Background I[1074.81 nm]

See [doc](https://docs.google.com/document/d/1ahVCUryLLN178ME2vRISd02gULGBL0Wy4Xr4ib29gAk/edit#) for current headers and comments.

**Comment by bberkeyU** [comment]
I dont think the extensions should have date-beg; this seems to imply to people that they can do some time sequencing between the extensions.  Early on, Maurice wasted a few hours trying to use these timestamps.  If it ever becomes important for a data user to know the timings between extensions, they will need a lot of background knowledge. They should probally be looking at the L0 data to derive their sequencing information.

Exptime should be in the primary header. The real-time code won't execute any recipe steps to change camera settings after data was taken in that recipe.  

I dont think the L1 headers should have mechanism positions in/out of the beam.  The L1 data comprises coronal, dark, and flat images that (other than the cover) have mixes for these in and out of the beam. We also should drop POLANGLE and RETANGLE since these are not meaningful for L1 data.

**Comment by jburkepile** [comment]
Its important for us to include timing information that includes 
extension header info on which images were combined in time in to create 
the level 1. This makes the data reproducible; otherwise it isn't. Do we 
not include the time in the extensions? With dawn down I am not sure 
where to find Mike's level1 data.

> Exptime should be in the primary header. The real-time code won't 
> execute any recipe steps to change camera settings after data was 
> taken in that recipe.
I am okay with this. If the real-time code changes this will need to be 
updated.

> I dont think the L1 headers should have mechanism positions in/out of 
> the beam. The L1 data comprises coronal, dark, and flat images that 
> (other than the cover) have mixes for these in and out of the beam. We 
> also should drop POLANGLE and RETANGLE since these are not meaningful 
> for L1 data.
I do look at these positions in UCoMP (and for KCor too); just to verify 
that everything is working as it ought to. I do not see any benefit in 
dropping these.

**Comment by mgalloy** [comment]
About the primary header...

Questions:

- [ ] Should the data be stored as a float or 16-bit integer?
- [ ] Should average occulter radius be `ORADIUS` or `RADIUS`?
- [ ] Remove `IMAGESCL`?
- [ ] Remove `CONTIN` keyword?
- [ ] Remove `FRAMERT` keyword?

Tasks:

- [ ] Report `SID_TIME` to 6 decimal places.
- [ ] Report `SECANT_Z` to 5 decimal places.
- [ ] Move ephemeris keywords next to each other.
- [ ] `RSUN` does not agree.
- [ ] Add `DATE-BEG` and `DATE-END` keywords.
- [ ] Add `LIN_CRCT` keyword.

**Comment by bberkeyU** [comment]
The sections look good.
I would break the Hardware info down into a couple more sections including SGS and Thermal.  And add a section for derived data products like MED_BACK and VCROSSTK.

We should keep the CONTIN keyword as it may be important for dealing with continuum features to know if we are getting red, blue, or both.

**Comment by bberkeyU** [comment]
> I don't think the L1 headers should have mechanism positions in/out of the beam. The L1 data comprises coronal, dark, and flat images that (other than the cover) have mixed for these in and out of the beam. We also should drop POLANGLE and RETANGLE since these are not meant for L1 data.

> I do look at these positions in UCoMP (and for KCor too); just to verify that everything is working as it ought to. I do not see any benefit in dropping these.

@jburkepile 
We tend to not change POLANGLE or RETANGLE while taking science data, but we could.  So if it is worth reporting in the L1 header it is not obvious to me what we should report.  

For example, if someone constructed a version of the 1074_01wave_2beam_16sums_4rep_BOTH.rcp recipe with a CALPOL move such as:  
CALPOL	0
DATA	RCAM	BOTH	1074.70	16
DATA	TCAM	BOTH	1074.70	16

DATA	RCAM	BOTH	1074.70	16
DATA	TCAM	BOTH	1074.70	16
CALPOL	45
DATA	RCAM	BOTH	1074.70	16
DATA	TCAM	BOTH	1074.70	16

DATA	RCAM	BOTH	1074.70	16
DATA	TCAM	BOTH	1074.70	16

Note: This recipe operationally makes no sense, but we could do it, or alternatively, an observer could trigger manually trigger this CALPOL move at the time described above.  But how would we report the POLANGLE position in the headers if it did get executed?

In the primary header, 0 or 45 are only 50% correct.  Further, both FITS extensions include data from all 8 L0 extensions, so 0 and 45 are equally invalid in the extensions.
Corona Stokes IQUV [1074.70 nm]
Background I [1074.70 nm]

My suggestion if we report this value in L1; we do it in the primary header as a string datatype.  If all of the L0 headers have the same float value we report that value in the header string.  If there is a change we report something like MOVING/MOVED/CHANGE/???    But since the pipeline processed this file as an L1 file, it means the CALOPTICS are out of the beam by definition.    Similar logic applies to RETANGLE.

**Comment by mgalloy** [comment]
There should be a `HISTORY` section that describes the steps in the processing:

    HISTORY Level 1 calibration and processing steps:
    HISTORY   - quality check
    HISTORY   - average like data
    HISTORY   - apply dark
    HISTORY   - apply gain
    HISTORY   - camera corrections such as hot pixel correction
    HISTORY   - correct continuum
    HISTORY   - demodulation
    HISTORY   - distortion correction
    HISTORY   - find the occulter
    HISTORY   - subtract continuum
    HISTORY   - deband
    HISTORY   - center images and rotate to north up
    HISTORY   - combine the cameras
    HISTORY   - polarimetric correction
    HISTORY   - correct for sky transmission
    HISTORY   - update FITS keywords
    HISTORY   - categorize GBU

**Comment by mgalloy** [comment]
Items from MLSO checking meeting today (22 May 2023):

- [ ] get rid of `SEMIDIAM` and `RSUN` primary keywords
- [ ] use either `SUN` or `EPHEM2`, but not both, and document which routine is used
- [ ] spell out "science" or "calibration" in `DATATYPE`
- [ ] check `MED_BACK` to `MED-BKG` with comment "median of background, i.e., the continuum"

**Comment by mgalloy** [comment]
Also, need to:

- [ ] move WCS section to immediately below Basic info section

**Comment by mgalloy** [comment]
Outstanding questions left about the level 1 headers:

What should the following comment be:

    COMMENT Continuum can be "red", "blue", or "both": "both" gives equal weight to
    COMMENT red and blue sides, "red" measures the continuum on the red side of the
    COMMENT WAVELNG by CONTOFF, "blue" measures the continuum on the blue side of
    COMMENT the WAVELNG by CONTOFF

@bberkeyU says:

> For red and blue the contributions are about 90/10. As written the comment seems to suggest more like all red or all blue. Do we want to make this more explicit here or take care of that in the user documents?

Maybe instead of "'red' measures the continuum on the red side", we say "'red' weights the continuum on the red side higher"?

@bberkeyU asks:

> Would it be interesting to record the emission /continuum fwhm in the header?


@bberkeyU asks:

> Should this be NUM_SUM to match the other similar keywords

**Comment by mgalloy** [comment]
@bberkeyU says:

> I think the L1 extension names look good.
>
> If I understand the lyot filter tuning correctly.  When the continuum is set to BOTH, the filter will pass 50% of the light from both continuum locations.  But when set to "red" it passes 90% of the light on the red continuum and 10% on the blue wing.  Can we find some language that describes these 10/90, 50/50, and 90/10 transmission profiles?

**Comment by mgalloy** [comment]
`CONTOFF` is column G, `FILTFWHM` is column F.

[UCoMP line list](https://docs.google.com/spreadsheets/d/1Q0_jR0VjrHrfG69g1KfLs7QPuYq-63aX/edit?pli=1#gid=2143146495)

**Comment by mgalloy** [comment]
Change `NUM_WAVE` and `NUM_BEAM` to `NUMWAVE` and `NUMBEAM`.

**Comment by mgalloy** [comment]
Primary header of `20220902.032356.ucomp.1074.l1.3.fts`:

    SIMPLE  =                    T / image conforms to FITS standard
    BITPIX  =                  -32 / bits per data value
    NAXIS   =                    0 / number of axes
    EXTEND  =                    T / file may contain extensions
    COMMENT --- Basic info ---
    ORIGIN  = 'NCAR/HAO'           / Institution
    INSTRUME= 'UCoMP'              / Upgraded Coronal Multichannel Polarimeter
    TELESCOP= '20 cm One Shot'     / NSO One Shot telescope
    LOCATION= 'MLSO'               / MLSO
    OBSSWID = '1.0.6   '           / data collection software ID
    DATE-OBS= '2022-09-02T03:23:56.48' / [UT] date/time when obs started
    DATE-END= '2022-09-02T03:26:22.50' / [UT] date/time when obs ended
    FILTER  = '1074    '           / [nm] prefilter wavelength region identifier
    OBJECT  = 'SUN     '           /
    COMMENT --- World Coordinate System (WCS) info ---
    WCSNAME = 'helioprojective-cartesian' / World Coordinate System (WCS) name
    CDELT1  =                2.944 / [arcsec/pixel] image X increment = platescale
    CDELT2  =                2.944 / [arcsec/pixel] image Y increment = platescale
    CRPIX1  =                640.5 / [pixel] occulter X center (index origin=1)
    CRVAL1  =                 0.00 / [arcsec] occulter X sun center
    CRUNIT1 = 'arcsec  '           / unit of CRVAL1
    CRPIX2  =                512.5 / [pixel] occulter Y center (index origin=1)
    CRVAL2  =                 0.00 / [arcsec] occulter Y sun center
    CRUNIT2 = 'arcsec  '           / unit of CRVAL2
    COMMENT --- Ephemeris info ---
    COMMENT Ephemeris calculations done by sun.pro
    SOLAR_P0=               21.318 / [deg] solar P angle applied (image has N up)
    SOLAR_B0=                7.204 / [deg] solar B-Angle
    SECANT_Z=             3.956955 / secant of the Zenith Distance
    SID_TIME=              0.09449 / [day fraction] GMST sidereal time
    CAR_ROT =                 2261 / Carrington Rotation Number
    JUL_DATE=    2459824.641620371 / [days] Julian date
    RSUN_OBS=               951.01 / [arcsec] solar radius using ref radius 959.63"
    R_SUN   =               323.03 / [pixel] solar radius
    COMMENT --- Level 1 processing info ---
    LEVEL   = 'L1      '           / level 1 calibrated
    DOI     = 'https://doi.org/xx.xxxx/xxxxxxxx' / Digital Object Identifier
    DATE_DP = '2023-08-17T06:30:55' / [UT] L1 processing date/time
    DPSWID  = '0.4.8-dev [4435a1ab*]' / L1 processing software (2023-08-16) [master]
    LIN_CRCT=                    F / camera linearity corrected
    DEMODV  =                    1 / demod coeffs version [2023-05-15T10:07:04Z]
    CONTSUB =                    T / whether the continuum was subtracted
    CAMERAS = 'both    '           / cameras used in processing
    BOPAL   =                14.80 / [B/Bsun] opal radiance
    BUNIT   = '1.0E-06 B/Bsun'     / brightness with respect to solar disk
    COMMENT --- Quality metrics ---
    VCROSSTK=             0.481139 / Stokes V crosstalk metric
    MED_BKG =               24.185 / [ppm] median of line center background annulus
    NUMSAT0O=                    0 / number of saturated pixels in onband RCAM
    NUMSAT1O=                    0 / number of saturated pixels in onband TCAM
    NUMSAT0C=                    0 / number of saturated pixels in bkg RCAM
    NUMSAT1C=                    0 / number of saturated pixels in bkg TCAM
    NUMNL0O =                 1809 / number of non-linear pixels in onband RCAM
    NUMNL1O =                 2667 / number of non-linear pixels in onband TCAM
    NUMNL0C =                 1902 / number of non-linear pixels in bkg RCAM
    NUMNL1C =                 1371 / number of non-linear pixels in bkg TCAM
    COMMENT --- Camera info ---
    EXPTIME =               80.000 / [ms] Exposure time
    FRAMERT =               10.691 / [Hz] Frequency of images
    GAIN    = 'high'               / Camera gain setting
    SAVEALL =                    F / [TF] Save all frames instead of summing
    TCAMID  = 'Raptor OWL1280 10055' / Unique ID of the TCAM (Camera 1)
    RCAMID  = 'Raptor OWL1280 10006' / Unique ID of the RCAM (Camera 0)
    TCAMLUT = ''                   / Unique ID of the LUT for TCAM
    RCAMLUT = ''                   / Unique ID of the LUT for RCAM
    TCAMNUC = 'Offset + gain corrected' / Camera Correction for TCAM
    RCAMNUC = 'Offset + gain corrected' / Camera Correction for RCAM
    NFRAME  =                  192 / total number of image frames in file
    REMFRAME=                    0 / number of bad frames removed
    NUMWAVE =                    3 / number of wavelengths
    NUMSUM  =                   16 / number of camera reads summed in an image frame
    NREPEAT =                    4 / number of repeats of wavelength scans
    NUMBEAM =                    2 / number of beams
    COMMENT Total camera reads in this file = NFRAME * NUMSUM where
    COMMENT   NFRAME = NUMWAVE * NREPEAT * NUMBEAM * 2(Cameras) * 4(Polarizations)
    COMMENT --- Observing info ---
    OBSERVER= 'Berkey'
    OBS_ID  = '1074_03wave_2beam_16sums_4rep_BOTH' / Name of current observation
    OBS_IDAU= ''                   / Author of the observing program
    OBS_IDDA= ' Wed Feb 16 13:55:59 2022' / Edit date of the observing program
    OBS_IDVE= '2d069f93becbc0fcab4a416df2d4ee4e' / [Md5 hash] Observation ver
    OBS_PLAN= 'all_wavelength_coronal.cbk' / Name of Current program
    OBS_PLAU= 'BERKEY'             / Author of the program
    OBS_PLDA= ''                   / Edit date of the observing plan
    OBS_PLVE= '702d3ebd18929e693c4eb03d1cb9f955' / [Md5 hash] Program ver
    COMMENT --- Hardware settings ---
    DARKID  = 'DARK SHUT 1'        / Dark Shutter ID
    O1ID    = 'O1#1'               / Unique ID of objective lens
    DIFFSRID= 'S1B'                / Unique ID of diffuser used (change to diffuser
    OCCLTRID= '27'                 / Unique ID of the current occulter
    FLCVNEG =               -7.000 / [V] Negative FeLC Drive voltage
    FLCVPOS =                7.000 / [V] Positive FeLC Drive voltage
    POLHOFF =            11021.000 / [counts] Offset in counts for the Cal Pololariz
    REDHOFF =             8694.000 / [counts] Offset in counts for the Cal Retarder
    T_COMPS =                    T / [TF] Lyot turning temperature compensation on
    WAVOFF  =                2.070 / [nm] Tuning offset for Lyot filter
    LCVRELX =                0.300 / [ms] Delay after LCVR turning before data
    FILTFWHM=                0.138 / [nm] Lyot FWHM
    CONTOFF =              1.25625 / [nm] continuum offset
    OCCLTR-X=               60.070 / Occulter X position
    OCCLTR-Y=                3.570 / Occulter Y position
    O1FOCUS =               60.230 / O1 focus position
    COMMENT --- Temperatures ---
    T_RACK  =               30.254 / [C] Computer Rack Temp
    T_LCVR1 =               34.580 / [C] Lyot LCVR1 Temp
    T_LCVR2 =               34.500 / [C] Lyot LCVR2 Temp
    T_LCVR3 =               34.583 / [C] Lyot LCVR3 Temp
    T_LNB1  =               34.583 / [C] LiNb1 Temp
    T_MOD   =               33.498 / [C] Modulator Temp
    T_LNB2  =               34.521 / [C] LiNb2 Temp
    T_LCVR4 =               34.541 / [C] Lyot LCVR4 Temp
    T_LCVR5 =               34.493 / [C] Lyot LCVR5 Temp
    T_BASE  =               31.865 / [C] Instrument Baseplate Temp
    TU_RACK =               30.517 / [C] Computer Rack Temp Unfiltered
    TU_LCVR1=               34.581 / [C] Lyot LCVR1 Temp Unfiltered
    TU_LCVR2=               34.500 / [C] Lyot LCVR2 Temp Unfiltered
    TU_LCVR3=               34.582 / [C] Lyot LCVR3 Temp Unfiltered
    TU_LNB1 =               34.585 / [C] LiNb1 Temp Unfiltered
    TU_MOD  =               33.781 / [C] Modulator Temp Unfiltered
    TU_LNB2 =               34.524 / [C] LiNb2 Temp Unfiltered
    TU_LCVR4=               34.546 / [C] Lyot LCVR4 Temp Unfiltered
    TU_LCVR5=               34.507 / [C] Lyot LCVR5 Temp Unfiltered
    TU_BASE =               32.115 / [C] Instrument Baseplate Temp Unfiltered
    T_C0ARR =                4.866 / [C] Camera 0 Sensor array temp
    T_C0PCB =               38.000 / [C] Camera 0 PCB board temp
    T_C1ARR =                4.958 / [C] Camera 1 Sensor array temp
    T_C1PCB =               38.000 / [C] Camera 1 PCB board temp
    COMMENT --- SGS info ---
    SGSSCINT=              4.03450 / [arcsec] SGS scintillation seeing estimate
    SGSDIMV =              7.56892 / [V] SGS Dim Mean
    SGSDIMS =              0.01590 / [V] SGS Dim Std
    SGSSUMV =              7.56679 / [V] SGS Sum Mean
    SGSSUMS =              0.01231 / [V] SGS Sum Std
    SGSRAV  =              0.00068 / [V] SGS RA Mean
    SGSRAS  =              0.02504 / [V] SGS RA Std
    SGSDECV =             -0.00042 / [V] SGS DEC Mean
    SGSDECS =              0.02986 / [V] SGS DEC Std
    SGSLOOP =              1.00000 / SGS Loop Fraction
    SGSRAZR =             -4.15500 / [V] SGS RA zero point
    SGSDECZR=             49.77916 / [V] SGS DEC zero point
    COMMENT --- Weather info ---
    WNDSPD  =                7.000 / [mph] wind speed
    WNDDIR  =               67.000 / [deg] wind direction
    COMMENT --- Occulter centering info ---
    COMMENT X/YOFFSET define position w.r.t. distortion corrected L0 images
    XOFFSET0=               -4.837 / [pixels] RCAM occulter x-offset from CRPIX1
    YOFFSET0=               -0.938 / [pixels] RCAM occulter y-offset from CRPIX2
    RADIUS0 =              332.682 / [pixels] RCAM occulter radius
    FITCHI0 =             0.283216 / [pixels] chi-squared for RCAM center fit
    XOFFSET1=               -6.737 / [pixels] TCAM occulter x-offset from CRPIX1
    YOFFSET1=               -2.247 / [pixels] TCAM occulter y-offset from CRPIX2
    RADIUS1 =              333.460 / [pixels] TCAM occulter radius
    FITCHI1 =             0.071829 / [pixels] chi-squared for TCAM center fit
    POST_ANG=              159.656 / [deg] post angle CCW from north
    RADIUS  =              333.071 / [pixels] occulter average radius
    IMAGESCL=             2.942261 / [arcsec/pixels] image scale for this file
    RCAMECC =               0.0722 / occulter eccentricity in RCAM
    TCAMECC =               0.0511 / occulter eccentricity in TCAM
    HISTORY
    HISTORY Level 1 calibration and processing steps:
    HISTORY   - quality check to determine if the file should be processed
    HISTORY   - average level 0 data with same onband and wavelength
    HISTORY   - apply dark correction
    HISTORY   - apply gain correction
    HISTORY   - camera corrections such as hot pixel correction
    HISTORY   - demodulation
    HISTORY   - distortion correction
    HISTORY   - find the occulter position and radius
    HISTORY   - subtract continuum
    HISTORY   - remove hoizontal/vertical bands
    HISTORY   - center images using occulter position and rotate to north up
    HISTORY   - combine the cameras
    HISTORY   - polarimetric correction
    HISTORY   - update FITS keywords
